/**
 * `@frontier-isles/renderer/pixi` — the WebGL engine entry point.
 *
 * Kept separate from the package root so that importing the root never loads
 * PixiJS. Import from here only where a GPU context is intended (apps/web L1).
 */

export { IsoStage, type IsoStageOptions } from './stage';
export {
  SceneStage,
  type SceneStageOptions,
  type TextureResolver,
  type ResolvedTexture,
  type SeaColors,
} from './scene-stage';
export { createSeaMesh, type SeaMesh, type SeaMeshOptions } from './sea-mesh';
export { RitualLayer, type RitualPoint, type RitualFireOptions } from './rituals';
export {
  AtlasStage,
  type AtlasStageOptions,
  type AtlasMetrics,
  type AtlasCameraPose,
  type AtlasStructureLensInput,
  type AtlasExplorerPose,
  type AtlasExplorerCamera,
  type AtlasExplorerFacing,
  type AtlasExplorerIsland,
  type AtlasExplorerCurrent,
  type AtlasExplorerBounds,
} from './atlas-stage';
export {
  zoomTier,
  tierBlend,
  deconflictLabels,
  islandPriority,
  placeholderClusters,
  makeFakeIslands,
  atlasCoastline,
  atlasCurrentGeometry,
  ATLAS_ALTITUDE_DISTANCE_WEIGHT,
  ATLAS_EXPLORER_APPROACH_DISTANCE,
  ATLAS_EXPLORER_CURRENT_SAMPLE_DISTANCE,
  ATLAS_EXPLORER_CURRENT_SIGNAL_DISTANCE,
  ATLAS_EXPLORER_MAX_SPEED,
  ATLAS_EXPLORER_SIGNAL_DISTANCE,
  atlasAltitudeZ,
  atlasCruiseScale,
  atlasCurrentId,
  atlasHash,
  facingToHeading,
  headingToFacing,
  vectorToFacing,
  atlasRng,
  assignAtlasAltitudes,
  assignAtlasHierarchy,
  atlasIslandLift,
  projectAtlasIslandY,
  nearestAtlasCurrentPoint,
  satelliteReveal,
  satelliteViewFactor,
  satelliteDisclosure,
  ATLAS_DOMAINS,
  ATLAS_ALTITUDE_BANDS,
  ATLAS_Y_TILT,
  ATLAS_BAND_LIFT,
  SATELLITE_REVEAL_START,
  SATELLITE_REVEAL_END,
  SATELLITE_DEEP_START,
  SATELLITE_DEEP_END,
  ATLAS_DOMAIN_FILL,
  ATLAS_DOMAIN_INK,
  ATLAS_STAGE_RADIUS,
  TIER_FAR_MAX,
  TIER_MID_MAX,
  TIER_BAND,
  FAKE_WORLD,
  type AtlasDomain,
  type AtlasAltitudeBand,
  type AtlasIslandRole,
  type AtlasTier,
  type AtlasIslandInput,
  type AtlasCluster,
  type AtlasContinent,
  type AtlasFogCell,
  type AtlasFlow,
  type AtlasCurrent,
  type AtlasCurrentGeometry,
  type AtlasCurrentNearestPoint,
  type LabelBox,
  type LabelVerdict,
} from './atlas-lod';
