/** Authored educational extensions, reviewed 2026-09-08. Separate from the
 * xFrontier corpus and research ledger. Every numerical apparatus is a toy. */
export type Bi = { zh: string; en: string };
export const bi = (zh: string, en: string): Bi => ({ zh, en });
export type StudyKind = 'proof' | 'causal' | 'compose' | 'theory' | 'matter' | 'cell' | 'calls' | 'erasure' | 'order' | 'benchmark';
export interface StudySource { title: string; url: string; year: string; finding: Bi; boundary: Bi }
export interface FieldStudy {
  kind: StudyKind; slug: string; island: Bi; title: Bi; question: Bi; invitation: Bi;
  choiceLabel: Bi; choices: Bi[]; valueLabel: Bi; min: number; max: number; initial: number; step: number;
  valueOptions?: Bi[]; rule: Bi; boundary: Bi; nextQuestion: Bi; sources: StudySource[];
  onward: { slug: string; reason: Bi; boundary: Bi };
}
export const FIELD_STUDIES: readonly FieldStudy[] = [
  {
    kind:'proof', slug:'formal-math', island:bi('形式化数学','Formal mathematics'),
    title:bi('证明通过，问题还在吗？','The proof holds. Does the question?'),
    question:bi('当量词被悄悄改写，正确的证明还在回答原来的问题吗？','When a quantifier changes, does a valid proof still answer the original question?'),
    invitation:bi('改写一个量词，再找一个反例。','Change a quantifier, then look for a counterexample.'),
    choiceLabel:bi('交给检查器的命题','Statement to check'),choices:[bi('所有 n','For every n'),bi('存在 n','There exists n')],
    valueLabel:bi('检查自然数 n','Inspect natural number n'),min:0,max:12,initial:2,step:1,
    rule:bi('考察命题 n² = n。逐个代入只能检验这个数；n = 2 是全称命题的反例，n = 0 或 1 是存在命题的见证。','Inspect n² = n. Substitution checks one number: n = 2 refutes the universal statement; n = 0 or 1 witnesses the existential statement.'),
    boundary:bi('这里计算等式并展示逻辑依赖，没有运行 Lean，也没有生成形式化证明。','This computes an equality and exposes logical dependencies. It does not run Lean or generate a formal proof.'),
    nextQuestion:bi('自动形式化时，怎样独立检查机器证明的命题与人的问题一致？','How could we independently check that an autoformalized statement preserves the human question?'),
    sources:[{title:'Theorem Proving in Lean 4 · Propositions and Proofs',url:'https://lean-lang.org/theorem_proving_in_lean4/Propositions-and-Proofs/',year:'Lean 4',finding:bi('Lean 以命题的类型及其证明项来表达和检查证明。','Lean expresses propositions as types and checks the corresponding proof terms.'),boundary:bi('类型检查的对象是写下来的命题；自然语言意图仍需核对。','The checked object is the written proposition; its natural-language intent still needs checking.')}],
    onward:{slug:'compositional-modeling',reason:bi('从命题的类型，走到模型接口的类型。','Move from proposition types to model interface types.'),boundary:bi('类型一致仍不足以保证模型描述了现实。','Matching types alone do not establish a model’s empirical validity.')},
  },
  {
    kind:'causal',slug:'causal-rep-learning',island:bi('因果表征','Causal representations'),
    title:bi('同一条相关线，两种因果世界','One correlation, two causal worlds'),
    question:bi('只看 X 与 Y 一起变化，怎样分清因果作用和共同原因？','If X and Y move together, how can we distinguish causation from a common cause?'),
    invitation:bi('把观察改成干预，看看两个世界在哪里分开。','Replace observation with intervention and see where two worlds diverge.'),
    choiceLabel:bi('获取数据的方式','How data are obtained'),choices:[bi('只观察','Observe'),bi('主动设定 X','Intervene on X')],
    valueLabel:bi('设定 X 的值','Value of X'),min:0,max:10,initial:7,step:1,
    rule:bi('构造两个世界：A 中 X = U，Y = X；B 中 X = U，Y = U。观察时两者完全重合。do(X = x) 切断进入 X 的箭头，U 仍均匀分布在 0–10。','Construct A: X = U, Y = X; and B: X = U, Y = U. Observations coincide. Under do(X = x), incoming arrows to X are cut and U remains uniform on 0–10.'),
    boundary:bi('这是已知变量的无噪声反例。真实表征学习还要从观测中识别潜变量，依赖额外假设。','This is a noiseless counterexample with known variables. Learning latent causal variables from observations requires additional assumptions.'),
    nextQuestion:bi('如果干预同时改变了相机、环境或另一个潜变量，可识别性还成立吗？','Does identifiability survive an intervention that also changes the camera, environment or another latent variable?'),
    sources:[{title:'Weakly supervised causal representation learning',url:'https://arxiv.org/abs/2203.16437',year:'2022',finding:bi('论文在特定假设下，用未知随机干预前后的配对样本建立可识别性。','Under stated assumptions, paired samples before and after unknown random interventions enable identifiability.'),boundary:bi('定理与简单图像实验不保证任意现实数据上的恢复。','The theorem and simple-image experiments do not guarantee recovery from arbitrary real-world data.')}],
    onward:{slug:'animal-ai-decode',reason:bi('动物交流也需要从声音相关走向行为干预。','Animal communication also calls for moving from correlations to behavioral interventions.'),boundary:bi('回放实验的行为证据不能直接套用潜变量可识别性定理。','Behavioral playback evidence does not automatically meet a latent-identifiability theorem’s assumptions.')},
  },
  {
    kind:'compose',slug:'compositional-modeling',island:bi('组合式科学建模','Compositional modeling'),
    title:bi('让接口守住一滴水','Make the interface conserve a drop'),
    question:bi('两个单独正确的模型，连接起来为什么会违反守恒？','Why can two individually correct models violate conservation when connected?'),
    invitation:bi('连接两座水库，检查流量的单位与守恒。','Connect two reservoirs and inspect units and conservation.'),
    choiceLabel:bi('右侧接口怎样读数','How the receiving interface reads the flow'),choices:[bi('同为 L / h','Both use L / h'),bi('误读为 L / min','Misread as L / min'),bi('加入单位转换','Convert units')],
    valueLabel:bi('左侧一小时流出量 / L','Outflow over one hour / L'),min:1,max:10,initial:4,step:1,
    rule:bi('A、B 初始各 100 L。左侧流出 q L/h；右侧若把相同数值当作 L/min，一小时就记入 60q。转换接口先除以 60，再按分钟累计。','A and B start at 100 L each. A loses q L/h. If B interprets q as L/min, it records 60q over an hour. An adapter first divides by 60 before minute-wise accumulation.'),
    boundary:bi('这是单位和守恒检查的最小算例，没有执行 Catlab，也没有建立真实水文模型。','This is a minimal units-and-conservation example. It neither executes Catlab nor builds a real hydrological model.'),
    nextQuestion:bi('如果单位相同，但两端的时间尺度或人群定义不同，接口还能直接拼接吗？','Can interfaces compose when units match but timescales or population definitions differ?'),
    sources:[{title:'An Algebraic Framework for Structured Epidemic Modeling',url:'https://arxiv.org/abs/2203.16345',year:'2022',finding:bi('用显式代数结构表达子模型与相互作用，支持模型组合和分层。','Explicit algebraic structure represents submodels and interactions, supporting composition and stratification.'),boundary:bi('本水库算例是编辑设计；论文的流行病模型没有被移植或运行。','The reservoir example is an authored teaching device; the paper’s epidemic models are not transplanted or executed.')}],
    onward:{slug:'self-learning-matter',reason:bi('守恒从模型接口走到物理电路的节点。','Follow conservation from model interfaces to physical circuit nodes.'),boundary:bi('满足守恒并不自动赋予网络学习能力。','Conservation alone does not give a network the ability to learn.')},
  },
  {
    kind:'theory',slug:'ai-theory-discovery',island:bi('AI 理论发现','AI theory discovery'),
    title:bi('把漂亮公式带出拟合区','Take a beautiful formula beyond the fit'),
    question:bi('两条在已知数据内贴合的公式，在哪次新测量中会分道扬镳？','Where would a new measurement separate two formulas that agree within the observed range?'),
    invitation:bi('移动测量位置，让插值与外推的区别显现。','Move the measurement point to reveal interpolation and extrapolation.'),
    choiceLabel:bi('比较的候选表达式','Candidate expression to compare'),choices:[bi('线性近似 x','Linear x'),bi('三阶近似 x − x³/6','Cubic x − x³/6')],
    valueLabel:bi('下一次测量位置 x','Next measurement position x'),min:0,max:3,initial:0.4,step:0.1,
    rule:bi('人为设定参考规律 y = sin(x)，已有观测只覆盖 0 ≤ x ≤ 0.5。比较 x 和 x − x³/6 的外推误差；没有在后台训练符号回归模型。','Set an illustrative reference y = sin(x), with observations limited to 0 ≤ x ≤ 0.5. Compare extrapolation errors of x and x − x³/6. No symbolic-regression model is trained here.'),
    boundary:bi('参考规律是预先写定的。误差来自当前公式计算，不是现实实验或 AI 发现成绩。','The reference law is chosen in advance. Errors are calculated from these formulas, not measured experimentally or achieved by an AI discovery system.'),
    nextQuestion:bi('当真实规律未知且观测有噪声，怎样选择最能区分候选理论的下一次实验？','When the true law is unknown and observations are noisy, which next experiment best distinguishes candidate theories?'),
    sources:[{title:'AI Feynman: a Physics-Inspired Method for Symbolic Regression',url:'https://arxiv.org/abs/1905.11481',year:'2020',finding:bi('算法结合神经网络拟合与对称性、可分性等线索，从数据中搜索符号表达式。','The algorithm combines neural-network fitting with clues such as symmetry and separability to search for symbolic expressions.'),boundary:bi('恢复已知方程的基准结果，与发现并验证未知自然规律是不同证据。','Recovering known benchmark equations is distinct from discovering and validating an unknown natural law.')}],
    onward:{slug:'adversarial-falsification-benchmark-science',reason:bi('把外推问题带到细胞扰动的留出评测。','Carry the extrapolation question into held-out cell perturbations.'),boundary:bi('公式近似误差不等于细胞模型的实际性能。','Formula approximation error is not a cell model’s measured performance.')},
  },
  {
    kind:'matter',slug:'self-learning-matter',island:bi('自学习物理网络','Self-learning matter'),
    title:bi('谁在改变电路的连接？','What changes the circuit’s connections?'),
    question:bi('物理系统到达平衡，与物理系统学会目标，有什么区别？','How does reaching physical equilibrium differ from learning a target?'),
    invitation:bi('比较固定电路与会更新电导的电路。','Compare a fixed circuit with one whose conductance updates.'),
    choiceLabel:bi('电导是否可改变','Can conductance change?'),choices:[bi('固定电导','Fixed conductance'),bi('按误差更新','Update from error')],
    valueLabel:bi('学习步数','Learning steps'),min:0,max:24,initial:8,step:1,
    rule:bi('无量纲分压器：输入 1，输出 v = g/(g+1)，目标 v* = 0.75，初始 g = 1。每步 g ← g + 0.8(v*−v)。固定电导时只重算平衡，不更新 g。','Dimensionless divider: input 1, output v = g/(g+1), target v* = 0.75, initial g = 1. Each step uses g ← g + 0.8(v*−v). A fixed circuit only re-evaluates equilibrium.'),
    boundary:bi('这是显式误差反馈的教学更新规则，不是论文的局部对比学习，也没有计算器件能耗或训练优势。','This explicit error-feedback teaching rule is not the paper’s local contrastive learning. It estimates neither device energy nor a training advantage.'),
    nextQuestion:bi('真正的局部学习中，目标误差怎样抵达每个元件，测量与更新又消耗多少能量？','In local learning, how does target information reach each element, and what do measurement and updates cost?'),
    sources:[{title:'Machine Learning Without a Processor: Emergent Learning in a Nonlinear Electronic Metamaterial',url:'https://arxiv.org/abs/2311.00537',year:'2024',finding:bi('研究构建由自调节非线性电阻元件组成的模拟网络，实现物理学习。','The study builds an analog learning network from self-adjusting nonlinear resistive elements.'),boundary:bi('器件实现有具体学习与测量机制，不能从“物理会平衡”直接推出。','The hardware requires particular learning and measurement mechanisms; equilibration by itself is insufficient.')}],
    onward:{slug:'minimal-genome',reason:bi('继续比较外部供给与系统内部实现的能力。','Continue comparing externally supplied capabilities with internally implemented ones.'),boundary:bi('电路的更新规则不是细胞适应机制。','A circuit update rule is not a mechanism of cellular adaptation.')},
  },
  {
    kind:'cell',slug:'minimal-genome',island:bi('最小基因组与细胞','Minimal genomes and cells'),
    title:bi('“最小”写在细胞里，还是环境里？','Is “minimal” in the cell or its environment?'),
    question:bi('从环境中拿走一项供给，原来可删去的功能是否重新成为必需？','If an environmental supply disappears, does a dispensable function become necessary?'),
    invitation:bi('改变外部供给，追踪细胞功能的依赖链。','Change external supply and trace a cell-function dependency.'),
    choiceLabel:bi('外部供给','External supply'),choices:[bi('供给前体 P','Precursor P supplied'),bi('撤去前体 P','Precursor P absent')],
    valueLabel:bi('内部合成功能','Internal synthesis function'),valueOptions:[bi('保留','Retained'),bi('删去','Removed')],min:0,max:1,initial:1,step:1,
    rule:bi('只定义一条抽象依赖：内部合成或外部供给得到 P；P 支持功能 G。切换供给与合成功能，观察能否沿这条图到达 G。P、G 不对应具体基因或培养配方。','Define one abstract dependency: synthesis OR external supply provides P; P enables G. Toggle both paths. P and G do not identify specific genes or a growth medium.'),
    boundary:bi('这是布尔依赖图，不能预测细胞存活、增殖或基因必需性。真实细胞还包含调控、动力学和未知功能。','This Boolean graph cannot predict survival, growth or gene essentiality. Real cells include regulation, dynamics and unknown functions.'),
    nextQuestion:bi('最低基因数量、稳定分裂、环境适应能力，应该被视为同一个“最小”目标吗？','Should minimum gene count, stable division and environmental adaptability be treated as one “minimal” objective?'),
    sources:[{title:'Genetic requirements for cell division in a genomically minimal cell',url:'https://cba.mit.edu/docs/papers/21.03.Cell.pdf',year:'2021',finding:bi('研究用基因组调整与单细胞成像，识别最小细胞中影响正常分裂的基因组合。','Genome changes and single-cell imaging identify combinations of genes affecting normal division in a minimal cell.'),boundary:bi('特定培养条件下的分裂表型，不给出所有环境通用的最小生命清单。','A division phenotype under particular culture conditions is not a universal minimum-life inventory.')}],
    onward:{slug:'adversarial-falsification-benchmark-science',reason:bi('去检验模型能否预测未见过的细胞扰动。','Ask whether a model predicts unseen cellular perturbations.'),boundary:bi('依赖图可达性与转录组预测需要不同验证。','Graph reachability and transcriptomic prediction require different validation.')},
  },
  {
    kind:'calls',slug:'animal-ai-decode',island:bi('动物交流解码','Decoding animal communication'),
    title:bi('把鸣声换个顺序','Change the order of the calls'),
    question:bi('识别出声音的组合结构，离理解动物如何使用它还有多远？','How far is recognizing sound structure from understanding how an animal uses it?'),
    invitation:bi('重排回放序列，分开听觉结构与行为证据。','Reorder a playback sequence; separate acoustic structure from behavioral evidence.'),
    choiceLabel:bi('回放条件','Playback condition'),choices:[bi('ABC','ABC'),bi('D','D'),bi('ABC → D','ABC → D'),bi('D → ABC','D → ABC')],
    valueLabel:bi('查看哪一层证据','Which evidence layer?'),valueOptions:[bi('声音序列','Sound sequence'),bi('论文行为观察','Reported behavior')],min:0,max:1,initial:0,step:1,
    rule:bi('按 Suzuki 等（2016）的回放条件重排符号：ABC、D、自然组合与逆序组合。行为层呈现论文的定性观察；图中的条长只区分音节组，不编码时长或反应概率。','Reorder symbolic conditions from Suzuki et al. (2016): ABC, D, natural and reversed combinations. The behavior layer reports qualitative observations. Bar lengths encode neither durations nor response probabilities.'),
    boundary:bi('没有播放或合成真实鸟声；这不是翻译器，也不能把日本山雀的实验结论直接推广到鲸或其他动物。','No real bird calls are played or synthesized. This is not a translator; findings in Japanese tits do not automatically generalize to whales or other animals.'),
    nextQuestion:bi('怎样设计新的回放对照，区分顺序敏感、熟悉度和可组合的意义？','Which new playback control could separate order sensitivity, familiarity and compositional meaning?'),
    sources:[{title:'Experimental evidence for compositional syntax in bird calls',url:'https://www.nature.com/articles/ncomms10986',year:'2016',finding:bi('在日本山雀中，ABC 与警戒扫描、D 与接近有关；自然组合与人工逆序引起不同反应。','In Japanese tits, ABC relates to scanning and D to approach; natural and artificially reversed combinations elicit different responses.'),boundary:bi('这是特定物种与回放条件下的证据，没有建立通用动物语言翻译。','This is evidence for one species under particular playback conditions, not a general translation of animal language.')}],
    onward:{slug:'causal-rep-learning',reason:bi('回到“观察什么”与“干预什么”的区别。','Return to the distinction between what is observed and what is intervened on.'),boundary:bi('语言意义不能仅由这个两变量因果算例决定。','The two-variable causal example cannot determine linguistic meaning.')},
  },
  {
    kind:'erasure',slug:'erasure-conversion-qubits-turning-loss',island:bi('量子擦除转换','Quantum erasure conversion'),
    title:bi('翻转与擦除，留下不同的不确定性','Flips and erasures leave different uncertainty'),
    question:bi('同样影响 k 个比特，未知位置的翻转与已知位置的擦除，留下多少种原始消息？','With k affected bits, how many original messages fit unknown-location flips versus known-location erasures?'),
    invitation:bi('比较翻转与擦除两种通道，观察原始消息的候选数。','Compare flip and erasure channels through their candidate original messages.'),
    choiceLabel:bi('错误通道','Error channel'),choices:[bi('未知位置的翻转','Flips at unknown locations'),bi('已知位置的擦除','Erasures at known locations')],
    valueLabel:bi('受影响位数 k','Number of affected bits k'),min:1,max:3,initial:1,step:1,
    rule:bi('经典 8 位偶校验算例。已知恰有 k 位翻转但位置未知时，有 C(8,k) 个原消息候选；若 k 个位置成为擦除且其余位可靠，偶校验留下 2^(k−1) 种填法。','Classical 8-bit even parity. With exactly k flips at unknown locations, there are C(8,k) possible originals. With k known erasures and reliable remaining bits, parity leaves 2^(k−1) fillings.'),
    boundary:bi('切换比较两种错误通道，并非为同一组翻转增加位置标记：二进制翻转若位置完全已知，反转这些位即可恢复。这里不模拟量子态、表面码或真实阈值；物理擦除标记也可能漏检或引入新错误。','The switch compares two error channels, not the same flips with added location flags: binary flips at fully known locations can simply be reversed. This does not simulate quantum states, surface codes or physical thresholds; physical erasure flags can miss errors or introduce new ones.'),
    nextQuestion:bi('当擦除标记不可靠，位置带来的信息收益何时抵不过探测代价？','When erasure flags are unreliable, when does their information benefit stop outweighing detection costs?'),
    sources:[{title:'Erasure conversion for fault-tolerant quantum computing in alkaline earth Rydberg atom arrays',url:'https://www.nature.com/articles/s41467-022-32094-6',year:'2022',finding:bi('提出把主要物理错误转成位置已知的擦除，并在指定噪声模型下进行电路级仿真。','Proposes converting dominant physical errors to located erasures and evaluates them with circuit-level simulations under a specified noise model.'),boundary:bi('文中的阈值依赖编码、门与噪声假设，不是所有量子平台的常数。','Thresholds depend on encoding, gates and noise assumptions; they are not constants for all quantum platforms.')}],
    onward:{slug:'formal-math',reason:bi('从错误位置的信息，回到验证器知道与不知道什么。','Move from error-location information to what a verifier knows and does not know.'),boundary:bi('信息约束是探索线索，不把两种验证方法等同。','Information constraints are an exploratory connection, not an equivalence of validation methods.')},
  },
  {
    kind:'order',slug:'hyperuniformity-hidden-order-disorder',island:bi('无序中的超均匀性','Hyperuniformity in disorder'),
    title:bi('把观察窗口慢慢放大','Slowly widen the observation window'),
    question:bi('近处看都没有整齐排列，远处的数量涨落会一样吗？','If neither pattern looks regular nearby, do their large-window number fluctuations agree?'),
    invitation:bi('用同一个圆形窗口取样两种点分布。','Sample two point patterns with the same circular window.'),
    choiceLabel:bi('点的生成规则','Point-generation rule'),choices:[bi('独立随机点','Independent random points'),bi('每格一粒、位置扰动','One jittered point per cell')],
    valueLabel:bi('观察半径 / 相对单位','Window radius / relative units'),min:5,max:30,initial:12,step:1,
    rule:bi('同为 196 点、100×100 周期区域、固定种子。在 100 个固定中心放圆窗，计算计数 N 的均值与方差。周期距离避免边缘截断；右侧条列显示各窗实际计数。','Both patterns contain 196 points in a periodic 100×100 region, with a fixed seed. Count N in circular windows at 100 fixed centers and compute mean and variance. Periodic distance avoids edge clipping; bars show actual window counts.'),
    boundary:bi('有限点集与有限窗口只能展示取样方法，不能证明无限尺度的超均匀性；大窗还受固定总点数影响。','Finite patterns and windows demonstrate sampling, not infinite-scale hyperuniformity. Large windows also feel the fixed total number of points.'),
    nextQuestion:bi('要把视觉印象变成超均匀性证据，还需要哪些尺度、样本与缺陷对照？','Which scales, samples and defect controls would turn a visual impression into evidence of hyperuniformity?'),
    sources:[{title:'Hyperuniform States of Matter',url:'https://arxiv.org/abs/1801.06924',year:'2018',finding:bi('超均匀性刻画大尺度密度涨落受到异常抑制，既可出现在有序系统，也可出现在某些无序系统。','Hyperuniformity describes unusually suppressed large-scale density fluctuations in ordered and certain disordered systems.'),boundary:bi('局部看起来均匀，或单一窗口方差较小，都不是充分判据。','Visual local uniformity or low variance at one window size is insufficient.')}],
    onward:{slug:'ai-theory-discovery',reason:bi('从观察尺度，继续追问候选规律在哪些范围成立。','Move from observation scale to the domain where a proposed law holds.'),boundary:bi('相似的取样问题不意味着背后存在同一物理机制。','Similar sampling questions do not establish a shared physical mechanism.')},
  },
  {
    kind:'benchmark',slug:'adversarial-falsification-benchmark-science',island:bi('细胞扰动预测评测','Cell perturbation benchmarks'),
    title:bi('留出的究竟是什么？','What exactly did you hold out?'),
    question:bi('模型见过同种扰动的其他细胞，还算预测了“未见扰动”吗？','If a model saw other cells with the same perturbation, did it predict an unseen perturbation?'),
    invitation:bi('亲手改变数据划分，揭开测试集中的熟面孔。','Change the split and expose familiar perturbations in the test set.'),
    choiceLabel:bi('留出方式','Hold-out unit'),choices:[bi('按细胞拆分','Hold out cells'),bi('按扰动拆分','Hold out perturbations'),bi('按细胞环境拆分','Hold out contexts')],
    valueLabel:bi('查看测试样本','Inspect a test sample'),valueOptions:[bi('第一个','First'),bi('第二个','Second')],min:0,max:1,initial:0,step:1,
    rule:bi('教学数据含 3 种扰动 A/B/C × 2 种细胞环境 X/Y × 2 个重复。仅改变训练与测试的成员关系，逐个检查扰动、环境以及二者组合是否在训练中出现。','Teaching data: 3 perturbations A/B/C × 2 contexts X/Y × 2 replicates. Change train/test membership, then inspect whether the perturbation, context and pair occur in training.'),
    boundary:bi('没有表达量、没有训练模型、没有性能排名。图展示的是评测问题怎样随划分改变。','There are no expression measurements, trained models or performance rankings here. The diagram shows how the evaluation question changes with the split.'),
    nextQuestion:bi('在相同数据、划分和指标下，新模型能否超过加性或均值基线？它究竟泛化了哪一层？','Under identical data, splits and metrics, can the model beat additive or mean baselines? At what level does it generalize?'),
    sources:[
      {title:'Deep-learning-based gene perturbation effect prediction does not yet outperform simple linear baselines',url:'https://www.nature.com/articles/s41592-025-02772-6',year:'2025',finding:bi('该比较指出：在其测试设置中，复杂深度模型未稳定超过简单基线。','This comparison found that complex deep models did not consistently outperform simple baselines in its evaluated settings.'),boundary:bi('结论受模型、数据和评测设置约束，不能推成深度学习永远无效。','This is bounded by the tested models, data and evaluation; it does not show that deep learning can never help.')},
      {title:'TxPert: using multiple knowledge graphs for prediction of transcriptomic perturbation effects',url:'https://www.nature.com/articles/s41587-026-03113-4',year:'2026',finding:bi('新的研究把多种知识图谱纳入扰动表示，报告在特定未见扰动及细胞环境任务中的改进。','A newer study integrates multiple knowledge graphs into perturbation representations and reports improvements on specified unseen-perturbation and context tasks.'),boundary:bi('不能跨论文直接比较成绩；应核对相同数据、基线与划分后再判断进展。','Scores cannot be compared directly across papers; progress requires matching datasets, baselines and splits.')},
    ],
    onward:{slug:'hyperuniformity-hidden-order-disorder',reason:bi('继续追问：改变取样方式，会怎样改变看见的规律？','Keep asking how a sampling choice changes the pattern we see.'),boundary:bi('评测泄漏与空间涨落不是同一个机制。','Evaluation leakage and spatial fluctuations are distinct mechanisms.')},
  },
];
export const fieldStudyFor = (slug: string) => FIELD_STUDIES.find(study => study.slug === slug);
