/**
 * GENERATED by scripts/generate-literature.mjs — do not edit by hand.
 *
 * Per-island reference lists projected from the xfrontier atlas evidence set,
 * deduplicated against each island's headline `citation`. Every entry is a
 * real, linkable source; entries missing a title, link, venue or year are
 * dropped rather than patched, because an uncheckable citation is worse than
 * none (§6 leavability: this travels with the island's problem.md).
 *
 * Browser consumers should load this entry point LAZILY — it belongs to the L1
 * island surface, not to the L0 atlas projection.
 */

export interface IslandReference {
  title: string;
  venue: string;
  year: number;
  url: string;
}

const LITERATURE_BY_SLUG: Record<string, IslandReference[]> = {
  "compositional-modeling": [
    { title: "Decapodes: A Diagrammatic Tool for Representing, Composing, and Computing Spatialized Partial Differential Equations", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2401.17432" },
    { title: "Compositional Modeling with Stock and Flow Diagrams", venue: "EPTCS 380 (ACT)", year: 2023, url: "https://doi.org/10.4204/eptcs.380.5" },
    { title: "Compositional epidemiological modeling using structured cospans", venue: "AlgebraicJulia", year: 2020, url: "https://blog.algebraicjulia.org/post/2020/10/structured-cospans/" },
  ],
  "dark-matter-paleo": [
    { title: "Mineral Detection of Neutrinos and Dark Matter 2025 Proceedings", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2508.20482" },
    { title: "Calorimetric approach to paleo-detection of dark matter", venue: "arXiv", year: 2026, url: "https://arxiv.org/abs/2605.13659" },
    { title: "Mineral Detection of Neutrinos and Dark Matter 2024. Proceedings", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2405.01626" },
  ],
  "bio-compute-thermo": [
    { title: "Is stochastic thermodynamics the key to understanding the energy costs of computation?", venue: "PNAS", year: 2024, url: "https://www.pnas.org/doi/10.1073/pnas.2321112121" },
    { title: "Stochastic thermodynamics for biological functions", venue: "Quantitative Biology (Wiley)", year: 2025, url: "https://onlinelibrary.wiley.com/doi/10.1002/qub2.75" },
    { title: "Nonequilibrium Thermodynamics for Biochemical Networks: Energetic Principles of Cellular Function", venue: "Annual Review of Biophysics", year: 2024, url: "https://www.annualreviews.org/content/journals/10.1146/annurev-biophys-021424-112247" },
  ],
  "formal-math": [
    { title: "The lean mathematical library", venue: "CPP 2020 (ACM SIGPLAN Int. Conf. on Certified Programs and Proofs)", year: 2020, url: "https://dl.acm.org/doi/10.1145/3372885.3373824" },
    { title: "Formalizing the proof of PFR in Lean4 using Blueprint: a short tour", venue: "What's new (Terence Tao)", year: 2023, url: "https://terrytao.wordpress.com/2023/11/18/formalizing-the-proof-of-pfr-in-lean4-using-blueprint-a-short-tour/" },
  ],
  "causal-rep-learning": [
    { title: "Score-based Causal Representation Learning with Interventions", venue: "arXiv:2301.08230", year: 2023, url: "https://arxiv.org/abs/2301.08230" },
    { title: "Score-based Causal Representation Learning: Linear and General Transformations", venue: "arXiv:2402.00849", year: 2024, url: "https://arxiv.org/abs/2402.00849" },
    { title: "Toward Causal Representation Learning", venue: "Proceedings of the IEEE", year: 2021, url: "https://arxiv.org/abs/2102.11107" },
  ],
  "triadic-percolation-connectivity-dynamical": [
    { title: "Triadic percolation on multilayer networks", venue: "arXiv / Phys. Rev. E", year: 2025, url: "https://arxiv.org/abs/2510.09341" },
  ],
  "experimental-determination-wavefunction-collapse": [
    { title: "New Limits on Spontaneous Wave Function Collapse Models with the XENONnT Data", venue: "arXiv / Physical Review Letters", year: 2022, url: "https://arxiv.org/abs/2209.15082" },
    { title: "The CSL Collapse Model and Spontaneous Radiation: An Update", venue: "Physical Review A (foundational)", year: 2005, url: "https://www.researchgate.net/publication/2183940_The_CSL_Collapse_Model_and_Spontaneous_Radiation_An_Update" },
  ],
  "coarse-graining-free-causal-emergence-dynamical": [
    { title: "Emergence and Causality in Complex Systems: A Survey of Causal Emergence and Related Quantitative Studies", venue: "Entropy / PMC", year: 2024, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10887681/" },
  ],
  "emergent-conventions-collective-bias-tipping": [
    { title: "The Dynamics of Social Conventions in LLM populations: Spontaneous Emergence, Collective Biases and Tipping Points", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2410.08948" },
    { title: "Emergent LLM behaviors are observationally equivalent to data leakage", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2505.23796" },
    { title: "Exploring the Topology and Memory of Consensus: How LLM Agents Agree, Fragment, or Settle When Forming Conventions", venue: "arXiv", year: 2026, url: "https://arxiv.org/abs/2606.04197" },
  ],
  "proximal-causal-identification-negative": [
    { title: "A confounding bridge approach for double negative control inference on causal effects", venue: "Statistical Theory and Related Fields", year: 2024, url: "https://www.tandfonline.com/doi/full/10.1080/24754269.2024.2390748" },
    { title: "Regression-Based Proximal Causal Inference (open access)", venue: "PMC / AJE", year: 2025, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12501610/" },
  ],
  "out-of-variable-generalization-partial-transportability": [
    { title: "Out-of-Variable Generalization for Discriminative Models (arXiv 2304.07896)", venue: "arXiv", year: 2023, url: "https://arxiv.org/abs/2304.07896" },
    { title: "Partial Transportability for Domain Generalization", venue: "arXiv (Google DeepMind & Columbia)", year: 2025, url: "https://www.alphaxiv.org/abs/2503.23605" },
  ],
  "category-theory-algebraic-theory": [
    { title: "Towards a Categorical Foundation of Deep Learning: A Survey", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2410.05353" },
  ],
  "ai-assisted-theorem-proving": [
    { title: "Solving olympiad geometry without human demonstrations", venue: "Nature", year: 2024, url: "https://www.nature.com/articles/s41586-023-06747-5" },
    { title: "Gold-medalist Performance in Solving Olympiad Geometry with AlphaGeometry2", venue: "Journal of Machine Learning Research", year: 2025, url: "https://jmlr.org/papers/volume26/25-1654/25-1654.pdf" },
  ],
  "cosmological-origin-arrow-time": [
    { title: "Thermodynamic Asymmetry in Time (Stanford Encyclopedia of Philosophy)", venue: "Stanford Encyclopedia of Philosophy", year: 2021, url: "https://plato.stanford.edu/entries/time-thermo/" },
    { title: "Arrow of Time without a Past Hypothesis", venue: "arXiv / Philosophy of Physics", year: 2018, url: "https://arxiv.org/abs/1809.04646" },
    { title: "Time and its arrow from quantum geometrodynamics", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2407.01727" },
  ],
  "gravitational-coupling-milligram-source": [
    { title: "Measuring gravity with milligram levitated masses", venue: "Science Advances", year: 2024, url: "https://www.science.org/doi/10.1126/sciadv.adk2949" },
  ],
  "proximal-causal-inference-negative-control": [
    { title: "Proximal Learning for Trials With External Controls: A Case Study in HIV Prevention", venue: "arXiv", year: 2026, url: "https://arxiv.org/pdf/2603.04544" },
    { title: "An Introduction to Proximal Causal Learning", venue: "arXiv → Statistical Science (2024)", year: 2020, url: "https://arxiv.org/abs/2009.10982" },
  ],
  "category-theoretic-compositional-scientific-modeling": [
    { title: "Compositional Modeling with Stock and Flow Diagrams", venue: "EPTCS (Applied Category Theory)", year: 2023, url: "https://doi.org/10.4204/eptcs.380.5" },
    { title: "Cartesian double theories: A double-categorical framework for categorical doctrines", venue: "Advances in Mathematics", year: 2024, url: "https://doi.org/10.1016/j.aim.2024.109630" },
  ],
  "living-wires": [
    { title: "Efficient long-range conduction in cable bacteria through nickel protein wires", venue: "Nature Communications", year: 2021, url: "https://www.nature.com/articles/s41467-021-24312-4" },
    { title: "Could Microbes Help Create Sustainable Electronics?", venue: "American Society for Microbiology", year: 2024, url: "https://asm.org/articles/2024/november/could-microbes-help-create-sustainable-electronics" },
    { title: "A highly conductive fibre network enables centimetre-scale electron transport in multicellular cable bacteria", venue: "Nature Communications", year: 2019, url: "https://www.nature.com/articles/s41467-019-12115-7" },
  ],
  "self-learning-matter": [
    { title: "Machine learning without a processor: Emergent learning in a nonlinear analog network", venue: "PNAS", year: 2024, url: "https://doi.org/10.1073/pnas.2319718121" },
    { title: "Machine Learning Without a Processor: Emergent Learning in a Nonlinear Electronic Metamaterial (preprint)", venue: "arXiv", year: 2023, url: "https://arxiv.org/abs/2311.00537" },
    { title: "A First, Physical System Learns Nonlinear Tasks Without a Traditional Computer Processor", venue: "Penn Engineering", year: 2024, url: "https://www.seas.upenn.edu/stories/a-first-physical-system-learns-nonlinear-tasks-without-a-traditional-computer-processor/" },
  ],
  "rock-battery": [
    { title: "Huff 'n' puff geothermal fracking: Earth batteries at 200% efficiency", venue: "New Atlas", year: 2024, url: "https://newatlas.com/energy/sage-geosystems-huff-puff/" },
    { title: "Sage's First 3-MW Geothermal Power and Energy Storage Project Will Feed ERCOT", venue: "POWER Magazine", year: 2025, url: "https://www.powermag.com/sages-first-3-mw-geothermal-power-and-energy-storage-project-will-feed-ercot/" },
    { title: "Sage Geosystems Technology (EarthStore / Geopressure Geothermal System)", venue: "Sage Geosystems", year: 2025, url: "https://www.sagegeosystems.com/technology" },
  ],
  "analog-solver": [
    { title: "Precise and scalable analogue matrix equation solving using resistive random-access memory chips", venue: "Nature Electronics", year: 2025, url: "https://www.nature.com/articles/s41928-025-01477-0" },
    { title: "Fully analog iteration for solving matrix equations with in-memory computing", venue: "Science Advances", year: 2025, url: "https://www.science.org/doi/10.1126/sciadv.adr6391" },
  ],
  "artificial-photosynthesis": [
    { title: "Solar-Driven CO2 Reduction Using a Semiconductor/Molecule Hybrid Photosystem: From Photocatalysts to a Monolithic Artificial Leaf", venue: "Accounts of Chemical Research", year: 2022, url: "https://pubs.acs.org/doi/10.1021/acs.accounts.1c00564" },
    { title: "Molecule/Semiconductor Hybrid Materials for Visible-Light CO2 Reduction: Design Principles and Interfacial Engineering", venue: "Accounts of Materials Research", year: 2022, url: "https://pubs.acs.org/doi/abs/10.1021/accountsmr.1c00060" },
    { title: "Current dilemma in photocatalytic CO2 reduction: real solar fuel production or false positive outcomings?", venue: "Carbon Neutrality", year: 2022, url: "https://link.springer.com/article/10.1007/s43979-022-00011-x" },
    { title: "Artificial photosynthesis: Emerging strategies for solar-to-fuel conversion", venue: "Inorganica Chimica Acta", year: 2026, url: "https://www.sciencedirect.com/science/article/abs/pii/S1387700326003692" },
  ],
  "info-chemistry": [
    { title: "Tabletop Molecular Communication: Text Messages through Chemical Signals", venue: "PLOS ONE", year: 2013, url: "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0082935" },
    { title: "Synthetic Cells Engaged in Molecular Communication: An Opportunity for Modelling Shannon- and Semantic-Information in the Chemical Domain", venue: "Frontiers in Communications and Networks", year: 2021, url: "https://www.frontiersin.org/journals/communications-and-networks/articles/10.3389/frcmn.2021.724597/full" },
    { title: "A Chemical Alphabet for Macromolecular Communications", venue: "Analytical Chemistry", year: 2018, url: "https://pubs.acs.org/doi/10.1021/acs.analchem.8b01716" },
  ],
  "chemical-vision": [
    { title: "Molecular Computation for Molecular Classification", venue: "JACS Au (PubMed)", year: 2023, url: "https://pubmed.ncbi.nlm.nih.gov/36709492/" },
    { title: "Scaling up molecular pattern recognition with DNA-based winner-take-all neural networks", venue: "Nature (PubMed)", year: 2018, url: "https://pubmed.ncbi.nlm.nih.gov/29973727/" },
  ],
  "photonic-time-crystals-space-time": [
    { title: "Observation of full momentum bandgap in photonic time crystals", venue: "arXiv (physics.optics)", year: 2026, url: "https://arxiv.org/abs/2604.17408" },
    { title: "Metasurface-based realization of photonic time crystals", venue: "Science Advances (PMC)", year: 2023, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10075962/" },
  ],
  "ferroelectric-in-memory-ising-annealer": [
    { title: "TReCiM: Lower Power and Temperature-Resilient Multibit 2FeFET-1T Compute-in-Memory Design", venue: "arXiv", year: 2025, url: "https://arxiv.org/pdf/2501.01052" },
  ],
  "magnetic-levitational-bioassembly-label-": [
    { title: "Scaffold-free, Label-free, and Nozzle-free Magnetic Levitational Bioassembler for Rapid Formative Biofabrication of 3D Tissues and Organs", venue: "International Journal of Bioprinting", year: 2020, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7557351/" },
    { title: "Biofabrication beyond Earth: Intelligent bioprinting for space medicine", venue: "Matter", year: 2025, url: "https://www.cell.com/matter/abstract/S2590-2385(25)00503-X" },
  ],
  "self-supervised-latent-world-models": [
    { title: "V-JEPA 2: Self-Supervised Video Models Enable Understanding, Prediction and Planning (publication page)", venue: "AI at Meta — Research", year: 2025, url: "https://ai.meta.com/research/publications/v-jepa-2-self-supervised-video-models-enable-understanding-prediction-and-planning/" },
  ],
  "neural-reconstruction-real-to-sim-policy-evaluation": [
    { title: "Real-to-Sim Robot Policy Evaluation with Gaussian Splatting Simulation of Soft-Body Interactions", venue: "arXiv (cs.RO)", year: 2025, url: "https://arxiv.org/abs/2511.04665" },
  ],
  "magic-state-cultivation-cheap": [
    { title: "Magic state cultivation on a superconducting quantum processor", venue: "arXiv (Google Quantum AI)", year: 2025, url: "https://arxiv.org/abs/2512.13908" },
    { title: "Magic States: A Key to Universal Fault-Tolerant Quantum Computing", venue: "PostQuantum", year: 2025, url: "https://postquantum.com/quantum-computing/magic-states/" },
  ],
  "erasure-conversion-qubits-turning-loss": [
    { title: "Developments in superconducting erasure qubits for hardware-efficient quantum error correction", venue: "arXiv", year: 2026, url: "https://arxiv.org/abs/2601.02183" },
    { title: "Fault-tolerant quantum architectures based on erasure qubits", venue: "arXiv", year: 2023, url: "https://arxiv.org/abs/2312.14060" },
  ],
  "stochastic-memristors-turning-device": [
    { title: "Enhancing IoT security with threshold switching-based unified security primitives", venue: "Nanotechnology (IOP)", year: 2025, url: "https://iopscience.iop.org/article/10.1088/1361-6528/adb980" },
    { title: "Concealable physical unclonable function generation and an in-memory encryption machine using vertical self-rectifying memristors", venue: "Nanoscale Horizons (RSC)", year: 2025, url: "https://pubs.rsc.org/en/content/articlelanding/2025/nh/d4nh00420e" },
  ],
  "clonal-hematopoiesis-chip-personalized": [
    { title: "Considering clonal hematopoiesis of indeterminate potential in space radiation risk analysis for hematologic cancers and cardiovascular disease", venue: "Communications Medicine", year: 2024, url: "https://www.nature.com/articles/s43856-023-00408-4" },
    { title: "Spaceflight as a cancer research catalyst", venue: "The Lancet Oncology", year: 2026, url: "https://www.thelancet.com/journals/lanonc/article/PIIS1470-2045(26)00135-X/abstract" },
  ],
  "soft-gradients-through-hard": [
    { title: "Learning Deployable Locomotion Control via Differentiable Simulation", venue: "CoRL 2025 (PMLR v305)", year: 2025, url: "https://proceedings.mlr.press/v305/schwarke25a.html" },
  ],
  "end-to-end-advantage-accounting-reckoning": [
    { title: "Topological data analysis on noisy quantum computers (end-to-end resource analysis)", venue: "arXiv 2209.09371", year: 2024, url: "https://arxiv.org/pdf/2209.09371" },
    { title: "Toward end-to-end quantum simulation for protein dynamics", venue: "arXiv 2411.03972", year: 2024, url: "https://arxiv.org/pdf/2411.03972" },
  ],
  "cable-bacteria-conductive-nanoribbons": [
    { title: "The organo-metal-like nature of long-range conduction in cable bacteria", venue: "Bioelectrochemistry", year: 2024, url: "https://doi.org/10.1016/j.bioelechem.2024.108675" },
    { title: "Metal scaffolds turn bacteria into live wires", venue: "Science (News)", year: 2025, url: "https://www.science.org/content/article/metal-scaffolds-turn-bacteria-live-wires" },
    { title: "Temperature-Dependent Characterization of Long-Range Conduction in Conductive Protein Fibers of Cable Bacteria", venue: "ACS Nano", year: 2024, url: "https://doi.org/10.1021/acsnano.4c12186" },
  ],
  "hyperuniformity-hidden-order-disorder": [
    { title: "Hyperuniformity and its generalizations", venue: "Physical Review E", year: 2016, url: "https://journals.aps.org/pre/abstract/10.1103/PhysRevE.94.022122" },
  ],
  "miyake-anchors": [
    { title: "A radiocarbon spike at 14 300 cal yr BP in subfossil trees provides the impulse response function of the global carbon cycle during the Late Glacial", venue: "Philosophical Transactions of the Royal Society A", year: 2023, url: "https://royalsocietypublishing.org/doi/10.1098/rsta.2022.0206" },
    { title: "Researchers identify largest ever solar storm in ancient 14,300-year-old tree rings", venue: "University of Leeds / EurekAlert", year: 2023, url: "https://www.eurekalert.org/news-releases/1003947" },
    { title: "Radiocarbon Spike 14,350 Years Ago Was Caused by Strongest Known Solar Storm, Study Confirms", venue: "Sci.News (reporting Earth and Planetary Science Letters)", year: 2025, url: "https://www.sci.news/astronomy/strongest-miyake-event-13911.html" },
  ],
  "code-dark-matter": [
    { title: "Widespread stop-codon recoding in bacteriophages may regulate translation of lytic genes", venue: "Nature Microbiology", year: 2022, url: "https://www.nature.com/articles/s41564-022-01128-6" },
    { title: "Driving through stop signs: predicting stop codon reassignment improves functional annotation of bacteriophages", venue: "ISME Communications", year: 2024, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11210395/" },
    { title: "Stop codon reassignments in the wild", venue: "Science", year: 2014, url: "https://www.science.org/doi/abs/10.1126/science.1250691" },
  ],
  "adar-sensors": [
    { title: "Programmable RNA sensing for cell monitoring and manipulation (CellREADR)", venue: "Nature", year: 2022, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10348343/" },
    { title: "Programmable eukaryotic protein synthesis with RNA sensors by harnessing ADAR (RADARS)", venue: "Nature Biotechnology", year: 2022, url: "https://pubmed.ncbi.nlm.nih.gov/36302988/" },
    { title: "RNA-programmable cell-type monitoring and manipulation in the human cortex with CellREADR", venue: "Cell Reports / bioRxiv", year: 2025, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12414115/" },
  ],
  "active-inference": [
    { title: "Active Inference for Physical AI Agents — An Engineering Perspective", venue: "arXiv", year: 2026, url: "https://arxiv.org/abs/2603.20927" },
    { title: "RxInfer.jl — Reactive real-time Bayesian inference (ReactiveBayes)", venue: "ReactiveBayes / JOSS", year: 2025, url: "https://rxinfer.com/" },
    { title: "Reactive Environments for Active Inference Agents with RxEnvironments.jl", venue: "arXiv", year: 2024, url: "https://arxiv.org/pdf/2409.11087" },
  ],
  "minimal-genome": [
    { title: "Minimal Cells—Real and Imagined", venue: "Cold Spring Harbor Perspectives in Biology", year: 2017, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5710109/" },
    { title: "JCVI-syn3.0 – A synthetic genome stripped bare!", venue: "Bioengineered", year: 2016, url: "https://www.tandfonline.com/doi/full/10.1080/21655979.2016.1175847" },
  ],
  "genome-writing": [
    { title: "Design of a synthetic yeast genome", venue: "Science", year: 2017, url: "https://www.science.org/doi/10.1126/science.aaf4557" },
    { title: "A spotlight on global collaboration in the Sc2.0 yeast consortium", venue: "Cell Genomics", year: 2023, url: "https://www.cell.com/cell-genomics/fulltext/S2666-979X(23)00276-8" },
    { title: "Methodological advances enabled by the construction of a synthetic yeast genome", venue: "Cell Reports Methods", year: 2024, url: "https://www.cell.com/cell-reports-methods/fulltext/S2667-2375(24)00092-4" },
  ],
  "deep-biosphere-extreme-life": [
    { title: "The Deep Rocky Biosphere: New Geomicrobiological Insights and Prospects", venue: "Frontiers in Microbiology", year: 2021, url: "https://www.frontiersin.org/journals/microbiology/articles/10.3389/fmicb.2021.785743/full" },
  ],
  "ice-sheet-basal-ecology-subglacial": [
    { title: "Microbial Community Structure of Subglacial Lake Whillans, West Antarctica", venue: "Frontiers in Microbiology", year: 2016, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5032586/" },
    { title: "Subglacial hydrology modulates basal sliding response of the Antarctic ice sheet to climate forcing", venue: "The Cryosphere", year: 2022, url: "https://tc.copernicus.org/articles/16/4537/2022/" },
    { title: "Physiological Ecology of Microorganisms in Subglacial Lake Whillans", venue: "Frontiers in Microbiology", year: 2016, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5081474/" },
  ],
  "in-tissue-spatial-functional-genomics": [
    { title: "Large-scale, spatially resolved panoramic CRISPR screening in native tissue environments using Perturb-DBiT", venue: "Nature Biotechnology", year: 2026, url: "https://www.nature.com/articles/s41587-026-03127-y" },
    { title: "Spatial perturb-seq: single-cell functional genomics within intact tissue architecture", venue: "Nature Communications", year: 2026, url: "https://www.nature.com/articles/s41467-026-69677-6" },
  ],
  "vivo-hematopoietic-stem-cell-editing": [
    { title: "In vivo genome editing of human haematopoietic stem cells for treatment of blood disorders using mRNA delivery", venue: "Nature Biomedical Engineering", year: 2025, url: "https://www.nature.com/articles/s41551-025-01480-y" },
  ],
  "falsifiable-consciousness-metrology-organoids": [
    { title: "Perturbational Complexity Index", venue: "Wikipedia (review of PCI literature)", year: 2024, url: "https://en.wikipedia.org/wiki/Perturbational_Complexity_Index" },
    { title: "Theoretical Neurobiology of Consciousness Applied to Human Cerebral Organoids", venue: "Cambridge Quarterly of Healthcare Ethics", year: 2024, url: "https://www.cambridge.org/core/journals/cambridge-quarterly-of-healthcare-ethics/article/theoretical-neurobiology-of-consciousness-applied-to-human-cerebral-organoids/13800A378FA638FE7B80B0C901ED41A5" },
  ],
  "genetically-encoded-rna-origami-cellular-hardware": [
    { title: "Genetic encoding and expression of RNA origami cytoskeletons in synthetic cells (preprint)", venue: "bioRxiv", year: 2024, url: "https://www.biorxiv.org/content/10.1101/2024.06.12.598448v1" },
  ],
  "adversarial-falsification-benchmark-science": [
    { title: "PerturBench: Benchmarking Machine Learning Models for Cellular Perturbation Analysis", venue: "arXiv / NeurIPS 2025 Datasets & Benchmarks", year: 2025, url: "https://arxiv.org/abs/2408.10609" },
    { title: "PerturBench (NeurIPS 2025 proceedings)", venue: "NeurIPS Datasets & Benchmarks Track", year: 2025, url: "https://proceedings.neurips.cc/paper_files/paper/2025/hash/8aee537279a66ced96319dfca3c00002-Abstract-Datasets_and_Benchmarks_Track.html" },
  ],
  "unknomics-systematically-studying-least-known": [
    { title: "Unknome database (v3) — ranks proteins by how little is known about them", venue: "MRC Laboratory of Molecular Biology", year: 2024, url: "https://unknome.mrc-lmb.cam.ac.uk/" },
    { title: "Screening Study IDs Functions for Conserved Proteins in 'Unknome' Collection", venue: "GenomeWeb", year: 2023, url: "https://www.genomeweb.com/proteomics-protein-research/screening-study-ids-functions-conserved-proteins-unknome-collection" },
  ],
  "ancient-dna-paleoproteomics": [
    { title: "Ancient protein analysis in archaeology", venue: "Science Advances", year: 2021, url: "https://www.science.org/doi/10.1126/sciadv.abb9314" },
    { title: "Neandertal and Denisovan DNA from Pleistocene sediments", venue: "Science", year: 2017, url: "https://www.science.org/doi/10.1126/science.aam9695" },
    { title: "Microstratigraphic preservation of ancient faunal and hominin DNA in Pleistocene cave sediments", venue: "PNAS", year: 2022, url: "https://www.pnas.org/doi/10.1073/pnas.2113666118" },
  ],
  "energy-limit-ecology-deep-subsurface-dark": [
    { title: "Microbial life under extreme energy limitation", venue: "Nature Reviews Microbiology", year: 2013, url: "https://www.nature.com/articles/nrmicro2939" },
    { title: "The contribution of water radiolysis to marine sedimentary life", venue: "Nature Communications", year: 2021, url: "https://www.nature.com/articles/s41467-021-21218-z" },
    { title: "Subsurface Life on Earth as a Key to Unlock Extraterrestrial Mysteries", venue: "PMC", year: 2024, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12712870/" },
  ],
  "3d-synthesizable-co-generation-joint": [
    { title: "SynCoGen code & SynSpace dataset", venue: "GitHub", year: 2025, url: "https://github.com/andreirekesh/SynCoGen" },
  ],
  "retrosynthesis-in-the-loop-direct-optimization-synthesizability": [
    { title: "TANGO: direct optimization of constrained synthesizability for generative molecular design", venue: "Nature Computational Science", year: 2026, url: "https://www.nature.com/articles/s43588-026-00959-1" },
  ],
  "animal-ai-decode": [
    { title: "Contextual and combinatorial structure in sperm whale vocalisations", venue: "Nature Communications", year: 2024, url: "https://www.nature.com/articles/s41467-024-47221-8" },
    { title: "Sperm Whale Phonetic Alphabet Proposed for the First Time", venue: "Project CETI", year: 2024, url: "https://www.projectceti.org/blog-posts/sperm-whale-phonetic-alphabet-proposed-for-the-first-time" },
    { title: "Exploring the mysterious alphabet of sperm whales", venue: "MIT News", year: 2024, url: "https://news.mit.edu/2024/csail-ceti-explores-sperm-whale-alphabet-0507" },
  ],
  "invertebrate-sentience": [
    { title: "The New York Declaration on Animal Consciousness", venue: "New York University", year: 2024, url: "https://sites.google.com/nyu.edu/nydeclaration/declaration" },
    { title: "The exploration of consciousness in insects", venue: "Philosophical Transactions of the Royal Society B", year: 2025, url: "https://royalsocietypublishing.org/rstb/article/380/1939/rstb.2024.0302/235190/The-exploration-of-consciousness-in-insects" },
    { title: "Honeybee Sentience: Scientific Evidence and Implications for EU Animal Welfare Policy", venue: "Animals (PMC)", year: 2025, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12298661/" },
  ],
  "verified-pqc": [
    { title: "Formally verifying Kyber Episode V: Machine-checked IND-CCA security and correctness of ML-KEM in EasyCrypt", venue: "CRYPTO 2024 / IACR ePrint", year: 2024, url: "https://eprint.iacr.org/2024/843" },
    { title: "formosa-crypto/formosa-mlkem — formally verified ML-KEM implementations (EasyCrypt + Jasmin)", venue: "GitHub / Formosa-Crypto", year: 2026, url: "https://github.com/formosa-crypto/formosa-mlkem" },
    { title: "Formally Verifying Kyber — Crypto 2024 IACR Artifact Archive", venue: "IACR Artifact Archive", year: 2024, url: "https://artifacts.iacr.org/crypto/2024/a3/readme.html" },
  ],
  "ai-theory-discovery": [
    { title: "Interpretable scientific discovery with symbolic regression: a review", venue: "Artificial Intelligence Review", year: 2024, url: "https://link.springer.com/article/10.1007/s10462-023-10622-0" },
    { title: "Artificial Intelligence in Physical Sciences: Symbolic Regression Trends and Perspectives", venue: "Archives of Computational Methods in Engineering", year: 2023, url: "https://link.springer.com/article/10.1007/s11831-023-09922-z" },
  ],
  "cross-species-umwelt": [
    { title: "The future of sensory substitution, addition, and expansion via haptic devices", venue: "Frontiers in Human Neuroscience", year: 2023, url: "https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2022.1055546/full" },
    { title: "Sensory augmentation: integration of an auditory compass signal into human perception of space", venue: "Scientific Reports", year: 2017, url: "https://www.nature.com/articles/srep42197" },
    { title: "Augmenting perception: How artificial intelligence transforms sensory substitution", venue: "Consciousness and Cognition", year: 2022, url: "https://www.sciencedirect.com/science/article/pii/S1053810022000125" },
    { title: "Learning New Sensorimotor Contingencies: Effects of Long-Term Use of Sensory Augmentation on the Brain and Conscious Perception", venue: "PLOS ONE", year: 2016, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5154504/" },
  ],
  "formal-unknown": [
    { title: "GAPMAP: Mapping Scientific Knowledge Gaps in Biomedical Literature Using Large Language Models", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2510.25055" },
    { title: "Knowledge graph revision in the context of unknown knowledge", venue: "PMC", year: 2024, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11226096/" },
    { title: "Atypical Combinations and Scientific Impact", venue: "Science", year: 2013, url: "https://www.science.org/doi/10.1126/science.1240474" },
  ],
  "dark-instrumentation": [
    { title: "Making the Invisible Visible: The Remarkable Journey of a Powerhouse Space Microscope", venue: "NASA Science", year: 2024, url: "https://science.nasa.gov/science-news/biological-physical/making-the-invisible-visible-the-remarkable-journey-of-a-powerhouse-space-microscope" },
    { title: "The Microscope & the Scientific Revolution", venue: "World History Encyclopedia", year: 2023, url: "https://www.worldhistory.org/article/2271/the-microscope--the-scientific-revolution/" },
    { title: "Why Science Does Not Know: A Brief History of (the Notion of) Scientific Ignorance", venue: "Journal for General Philosophy of Science", year: 2021, url: "https://www.researchgate.net/publication/356614601" },
    { title: "Dark Data: Why What You Don't Know Matters", venue: "Technometrics", year: 2023, url: "https://www.tandfonline.com/doi/full/10.1080/00401706.2022.2163804" },
  ],
  "evaluation-awareness-how-models": [
    { title: "Probing and Steering Evaluation Awareness of Language Models", venue: "arXiv", year: 2025, url: "https://arxiv.org/html/2507.01786v2" },
    { title: "Evaluation Awareness: Why Frontier AI Models Are Getting Harder to Test", venue: "Institute for AI Policy and Strategy", year: 2025, url: "https://www.iaps.ai/research/evaluation-awareness-why-frontier-ai-models-are-getting-harder-to-test" },
  ],
  "complexity-theoretic-debate-provable-protocols": [
    { title: "Scalable AI Safety via Doubly-Efficient Debate", venue: "arXiv / ICML 2024", year: 2024, url: "https://arxiv.org/pdf/2311.14125" },
  ],
  "biological-computationalism-substrate-inseparability-criterion": [
    { title: "Why consciousness can't be reduced to code", venue: "ScienceDaily", year: 2025, url: "https://www.sciencedaily.com/releases/2025/12/251224032351.htm" },
  ],
  "calibration-problem-artificial-consciousness": [
    { title: "Identifying indicators of consciousness in AI systems", venue: "Trends in Cognitive Sciences", year: 2025, url: "https://www.sciencedirect.com/science/article/pii/S1364661325002864" },
  ],
  "verifiable-reward-discovery-agents-pushing": [
    { title: "AlphaEvolve: A coding agent for scientific and algorithmic discovery", venue: "Google DeepMind", year: 2025, url: "https://deepmind.google/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/" },
    { title: "AlphaResearch: Accelerating New Algorithm Discovery with Language Models", venue: "arXiv", year: 2025, url: "https://arxiv.org/pdf/2511.08522" },
  ],
  "differentiable-manufacturing-simulation-gradient-based": [
    { title: "Differentiable simulation for material thermal response design in additive manufacturing processes", venue: "Additive Manufacturing (Elsevier)", year: 2022, url: "https://www.sciencedirect.com/science/article/abs/pii/S2214860422007266" },
    { title: "Differentiable simulation and optimization of particle-fluid flows using graph neural networks", venue: "Powder Technology (Elsevier)", year: 2025, url: "https://www.sciencedirect.com/science/article/abs/pii/S0032591025005388" },
  ],
  "epistemic-boundaries-autonomous-science": [
    { title: "Xenoepistemics: A Non-Anthropocentric Framework for Machine Knowledge", venue: "Philosophies (MDPI)", year: 2026, url: "https://ddd.uab.cat/pub/artpub/2026/328145/philosophies_2026v11n2p57.pdf" },
    { title: "Of opaque oracles: epistemic dependence on AI in science poses no novel problems for social epistemology", venue: "Synthese", year: 2025, url: "https://link.springer.com/article/10.1007/s11229-025-04930-x" },
  ],
  "developmental-interpretability-singular-learning": [
    { title: "Differentiation and Specialization of Attention Heads via the Refined Local Learning Coefficient", venue: "ICLR 2025", year: 2025, url: "https://arxiv.org/abs/2410.02984" },
    { title: "devinterp — Tools for studying developmental interpretability (Timaeus)", venue: "GitHub / Timaeus", year: 2024, url: "https://github.com/timaeus-research/devinterp" },
  ],
  "structural-enforcement-statistical-rigor": [
    { title: "AIGS: Generating Science from AI-Powered Automated Falsification", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2411.11910" },
    { title: "The Need for Verification in AI-Driven Scientific Discovery", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2509.01398" },
  ],
  "idiographic-dynamic-network-psychology": [
    { title: "Time-Varying Network Models for the Temporal Dynamics of Depressive Symptomatology in Patients With Depressive Disorders", venue: "JMIR Mental Health", year: 2024, url: "https://mental.jmir.org/2024/1/e50136" },
    { title: "A dynamical systems framework for precision psychiatry", venue: "PMC / Molecular Psychiatry", year: 2025, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12484574/" },
  ],
  "self-play-dueling-agents-autonomous": [
    { title: "Automated conjecturing in mathematics with TxGraffiti", venue: "arXiv (Davila)", year: 2024, url: "https://arxiv.org/abs/2409.19379" },
  ],
  "stimulated-raman-activated-cell-ejection": [
    { title: "Artificial Intelligence-Assisted Automatic Raman-Activated Cell Sorting (AI-RACS) for Mining Functional Microorganisms", venue: "Analytical Chemistry", year: 2024, url: "https://pubs.acs.org/doi/abs/10.1021/acs.analchem.4c03213" },
  ],
  "complexity-consciousness-proxy-brain": [
    { title: "In vitro neurons learn and exhibit sentience when embodied in a simulated game-world (DishBrain)", venue: "Neuron (Cell Press)", year: 2022, url: "https://www.cell.com/neuron/fulltext/S0896-6273(22)00806-6" },
    { title: "A Computational Perspective on NeuroAI and Synthetic Biological Intelligence", venue: "arXiv", year: 2025, url: "https://arxiv.org/pdf/2509.23896" },
  ],
  "quantum-biological-hybrid-computing": [
    { title: "Do photosynthetic complexes use quantum coherence to increase their efficiency? Probably not", venue: "Journal of Physical Chemistry Letters", year: 2021, url: "https://pubmed.ncbi.nlm.nih.gov/33597236/" },
    { title: "Quantum coherent dynamics in photosynthetic protein complexes", venue: "Chemical Society Reviews", year: 2026, url: "https://pubs.rsc.org/en/content/articlehtml/2026/cs/d5cs00948k" },
  ],
  "metagenomic-foundation-models-reading-function": [
    { title: "Uncovering the Genomic Manifold via Scalable Learning from the Global Microbiome (GenomeOcean)", venue: "bioRxiv", year: 2025, url: "https://doi.org/10.1101/2025.01.30.635558" },
    { title: "Deciphering enzymatic potential in metagenomic reads through DNA language models (REMME/REBEAN)", venue: "Nucleic Acids Research", year: 2025, url: "https://doi.org/10.1093/nar/gkaf836" },
  ],
  "airborne-edna-biodiversity-surveys": [
    { title: "Airborne environmental DNA captures terrestrial vertebrate diversity in nature", venue: "Molecular Ecology Resources", year: 2023, url: "https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.13840" },
    { title: "Airborne eDNA captures three decades of ecosystem biodiversity", venue: "bioRxiv (preprint)", year: 2023, url: "https://www.biorxiv.org/content/10.1101/2023.12.06.569882v1" },
  ],
  "engineered-living-materials-elms": [
    { title: "Engineered Living Materials For Sustainability", venue: "Chemical Reviews", year: 2023, url: "https://pubs.acs.org/doi/abs/10.1021/acs.chemrev.2c00512" },
    { title: "Engineered Living Materials: Taxonomies and Emerging Trends", venue: "Trends in Biotechnology", year: 2020, url: "https://www.sciencedirect.com/science/article/abs/pii/S0167779920302730" },
    { title: "Strength in diversity: unlocking the full potential of engineered living materials with multistrain collaboration", venue: "FEMS Microbiology Reviews", year: 2025, url: "https://academic.oup.com/femsre/article/doi/10.1093/femsre/fuaf055/8316143" },
  ],
  "programmable-dna-hydrogels": [
    { title: "Design and application of stimuli-responsive DNA hydrogels: A review", venue: "Frontiers in Chemistry", year: 2022, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9493390/" },
    { title: "Advances in programmable DNA nanostructures enabling stimuli-responsive drug delivery and multimodal biosensing", venue: "Nanoscale Advances", year: 2025, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12203123/" },
  ],
  "anthrobots-self-assembling-biobots-from": [
    { title: "With Living Robots, Scientists Unlock Cells' Power to Heal", venue: "Tufts Now", year: 2024, url: "https://now.tufts.edu/2024/03/22/living-robots-scientists-unlock-cells-power-heal" },
    { title: "Scientists build tiny biological robots from human cells", venue: "Wyss Institute, Harvard", year: 2023, url: "https://wyss.harvard.edu/news/scientists-build-tiny-biological-robots-from-human-cells/" },
  ],
  "xenobots": [
    { title: "Kinematic self-replication in reconfigurable organisms", venue: "PNAS", year: 2021, url: "https://www.pnas.org/doi/10.1073/pnas.2112672118" },
  ],
  "cell-digital-twins-virtual-cells": [
    { title: "Towards multimodal foundation models in molecular cell biology", venue: "Nature", year: 2025, url: "https://www.nature.com/articles/s41586-025-08710-y" },
    { title: "Grow AI virtual cells: three data pillars and closed-loop learning", venue: "Cell Research", year: 2025, url: "https://www.nature.com/articles/s41422-025-01101-y" },
  ],
  "environment-health-exposome-monitoring": [
    { title: "Features and Practicability of the Next-Generation Sensors and Monitors for Exposure Assessment to Airborne Pollutants: A Systematic Review", venue: "Sensors", year: 2021, url: "https://doi.org/10.3390/s21134513" },
    { title: "An Assessment of Multipollutant Exposures Using Silicone Wristbands Among Bangladeshi Youth", venue: "International Journal of Environmental Research and Public Health", year: 2024, url: "https://doi.org/10.3390/ijerph21121691" },
  ],
  "individual-differences-in-taste-and": [
    { title: "Genetic variation in the human olfactory receptor OR5AN1 associates with the perception of musks", venue: "Chemical Senses", year: 2023, url: "https://doi.org/10.1093/chemse/bjac037" },
    { title: "Differential Activation of TAS2R4 May Recover Ability to Taste Propylthiouracil for Some TAS2R38 AVI Homozygotes", venue: "Nutrients", year: 2024, url: "https://doi.org/10.3390/nu16091357" },
  ],
  "cross-species-cognition-and-comparative": [
    { title: "Bringing Comparative Cognition To Computers", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2503.02882" },
    { title: "The Animal-AI Environment: A virtual laboratory for comparative cognition and artificial intelligence research", venue: "Behavior Research Methods", year: 2025, url: "https://link.springer.com/article/10.3758/s13428-025-02616-3" },
  ],
  "solar-radiation-management-modeling-governance": [
    { title: "The potential environmental and climate impacts of stratospheric aerosol injection: a review", venue: "Environmental Science: Atmospheres", year: 2024, url: "https://pubs.rsc.org/en/content/articlelanding/2024/ea/d3ea00134b" },
    { title: "The Risk of Termination Shock From Solar Geoengineering", venue: "Earth's Future", year: 2018, url: "https://agupubs.onlinelibrary.wiley.com/doi/10.1002/2017EF000735" },
  ],
  "gene-drive-modeling-ethics": [
    { title: "An Ethical Overview of the CRISPR-Based Elimination of Anopheles gambiae to Combat Malaria", venue: "AJOB Neuroscience / Yale Journal of Biology and Medicine", year: 2022, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9463432/" },
    { title: "Daisy-chain gene drives: The role of low cut-rate, resistance mutations, and maternal deposition", venue: "PLOS Genetics", year: 2022, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9521892/" },
    { title: "Gene drive-based population suppression in the malaria vector Anopheles stephensi", venue: "Nature Communications", year: 2025, url: "https://www.nature.com/articles/s41467-025-56290-2" },
  ],
  "engineering-pathways-to-fusion-energy": [
    { title: "Commonwealth Fusion Systems HTS magnets technology", venue: "Commonwealth Fusion Systems (institutional)", year: 2024, url: "https://cfs.energy/technology/hts-magnets/" },
    { title: "Bringing Fusion Energy to the Grid: Challenges and Pathways", venue: "Kleinman Energy Center, University of Pennsylvania", year: 2023, url: "https://kleinmanenergy.upenn.edu/research/publications/bringing-fusion-energy-to-the-grid-challenges-and-pathways/" },
    { title: "Commonwealth Fusion Systems fusion engineering progress", venue: "Engineering", year: 2024, url: "https://www.engineering.org.cn/engi/EN/PDF/10.1016/j.eng.2024.12.002" },
  ],
  "astrobiology-and-the-origin-of": [
    { title: "The origin of life as a planetary phenomenon", venue: "Science Advances", year: 2020, url: "https://www.science.org/doi/10.1126/sciadv.aax3419" },
    { title: "A Review on Hypothesized Metabolic Pathways on Europa and Enceladus: Space-Flight Detection Considerations", venue: "Life", year: 2023, url: "https://www.mdpi.com/2075-1729/13/8/1726" },
  ],
  "subsurface-oceans-of-icy-moons": [
    { title: "Abundant phosphorus expected for possible life in Enceladus's ocean", venue: "PNAS", year: 2022, url: "https://www.pnas.org/doi/10.1073/pnas.2201388119" },
    { title: "A Review on Hypothesized Metabolic Pathways on Europa and Enceladus: Space-Flight Detection Considerations", venue: "Astrobiology", year: 2023, url: "https://www.researchgate.net/publication/373088825_A_Review_on_Hypothesized_Metabolic_Pathways_on_Europa_and_Enceladus_Space-Flight_Detection_Considerations" },
    { title: "Europa's ocean: potential for extraterrestrial chemoautotrophy", venue: "Frontiers in Astronomy and Space Sciences", year: 2025, url: "https://www.frontiersin.org/journals/astronomy-and-space-sciences/articles/10.3389/fspas.2025.1694079/full" },
  ],
  "sociogenomics": [
    { title: "Polygenic Indices (a.k.a. Polygenic Scores) in Social Science: A Guide for Interpretation and Evaluation", venue: "Sociological Methodology", year: 2024, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11293310/" },
    { title: "Social and Behavioral Genomics: On the Ethics of the Research and Its Downstream Applications", venue: "Annual Review of Genomics and Human Genetics", year: 2025, url: "https://www.annualreviews.org/content/journals/10.1146/annurev-genom-011224-015733" },
  ],
  "autonomous-ai-scientist-ai-reviewer": [
    { title: "Open Conference of AI Agents for Science (Agents4Science) — Paper Submissions", venue: "Stanford University / Together AI", year: 2025, url: "https://agents4science.stanford.edu/submissions.html" },
    { title: "The AI Scientist-v2: Workshop-Level Automated Scientific Discovery via Agentic Tree Search", venue: "Sakana AI (technical report)", year: 2025, url: "https://pub.sakana.ai/ai-scientist-v2/paper/paper.pdf" },
  ],
  "zero-knowledge-verifiable-scientific-computation": [
    { title: "A Survey of Zero-Knowledge Proof Based Verifiable Machine Learning", venue: "arXiv / AI Review (Springer)", year: 2025, url: "https://arxiv.org/abs/2502.18535" },
    { title: "A Framework for Cryptographic Verifiability of End-to-End AI Pipelines", venue: "arXiv", year: 2025, url: "https://arxiv.org/pdf/2503.22573" },
  ],
  "human-machine-collaborative-scientific-discovery": [
    { title: "Accelerating science with human-aware artificial intelligence", venue: "Nature Human Behaviour", year: 2023, url: "https://www.nature.com/articles/s41562-023-01648-z" },
    { title: "Human-machine collaboration for improving semiconductor process development", venue: "Nature", year: 2023, url: "https://www.nature.com/articles/s41586-023-05773-7" },
  ],
  "the-empirical-science-of-human": [
    { title: "Does the Whole Exceed its Parts? The Effect of AI Explanations on Complementary Team Performance", venue: "ACM CHI", year: 2021, url: "https://aiweb.cs.washington.edu/ai/pubs/bansal-chi21.pdf" },
    { title: "Complementarity in Human-AI Collaboration: Concept, Sources, and Evidence", venue: "arXiv", year: 2024, url: "https://arxiv.org/html/2404.00029v2" },
  ],
  "ai-mediated-collective-deliberation": [
    { title: "AI can help humans find common ground in democratic deliberation (publication page)", venue: "Google DeepMind", year: 2024, url: "https://deepmind.google/research/publications/65220/" },
    { title: "google-deepmind/habermas_machine — dataset & code", venue: "GitHub (official code)", year: 2024, url: "https://github.com/google-deepmind/habermas_machine" },
  ],
  "ai-mediated-deliberation-and-machine": [
    { title: "Sensemaking by Jigsaw — open-source LLM tools for large-scale public input", venue: "Google Jigsaw (GitHub)", year: 2024, url: "https://github.com/Jigsaw-Code/sensemaking-tools" },
    { title: "Talk to the City — open-source LLM interface for collective deliberation", venue: "AI Objectives Institute", year: 2024, url: "https://ai.objectives.institute/talk-to-the-city-1" },
  ],
  "electro-agriculture-and-light-free": [
    { title: "A hybrid inorganic-biological artificial photosynthesis system for energy-efficient food production", venue: "Nature Food", year: 2022, url: "https://doi.org/10.1038/s43016-022-00530-x" },
    { title: "With 'electro-agriculture,' plants can produce food in the dark and with 94% less land, bioengineers say", venue: "Phys.org", year: 2024, url: "https://phys.org/news/2024-10-electro-agriculture-food-dark-bioengineers.html" },
  ],
  "animal-free-drug-safety-science": [
    { title: "Advancing FDA New Approach Methodologies from animal models through digital twins", venue: "npj Digital Medicine", year: 2026, url: "https://www.nature.com/articles/s41746-026-02476-x" },
    { title: "New Approach Methodologies (NAMs)", venue: "U.S. FDA", year: 2025, url: "https://www.fda.gov/science-research/science-and-research-special-topics/new-approach-methodologies-nams" },
  ],
  "aging-biology-and-longevity-science": [
    { title: "Targeting ageing with rapamycin and its derivatives in humans: a systematic review", venue: "The Lancet Healthy Longevity", year: 2023, url: "https://www.thelancet.com/journals/lanhl/article/PIIS2666-7568(23)00258-1/fulltext" },
    { title: "Targeting Senescence: A Review of Senolytics and Senomorphics in Anti-Aging Interventions", venue: "Biomolecules (MDPI)", year: 2025, url: "https://www.mdpi.com/2218-273X/15/6/860" },
    { title: "A Critical Review of the Evidence That Metformin Is a Putative Anti-Aging Drug That Enhances Healthspan and Extends Lifespan", venue: "Frontiers in Endocrinology", year: 2021, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8374068/" },
  ],
  "digitizing-olfaction-and-the-principal": [
    { title: "A principal odor map unifies diverse tasks in human olfactory perception (full text)", venue: "PMC", year: 2023, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11898014/" },
    { title: "New York Smells: A Large Multimodal Dataset for Olfaction", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2511.20544" },
  ],
  "interactive-molecular-dynamics-in-vr": [
    { title: "NanoVer Server: A Python Package for Serving Real-Time Multi-User Interactive Molecular Dynamics in Virtual Reality", venue: "Journal of Open Source Software", year: 2025, url: "https://joss.theoj.org/papers/10.21105/joss.08118.pdf" },
    { title: "nanover-server-py: Interactive Molecular Dynamics (iMD) in VR", venue: "GitHub (IRL2)", year: 2025, url: "https://github.com/IRL2/nanover-server-py" },
  ],
  "ai-mediated-deliberation-and-consensus": [
    { title: "Online Deliberation Platform — Deliberative Democracy Lab", venue: "Stanford University", year: 2025, url: "https://deliberation.stanford.edu/tools-resources/online-deliberation-platform" },
  ],
  "a-quantitative-science-of-serendipity": [
    { title: "Serendipity: The Unexpected in Science", venue: "MIT Press", year: 2024, url: "https://direct.mit.edu/books/book/5821/SerendipityThe-Unexpected-in-Science" },
    { title: "Role of chance in scientific discoveries", venue: "Wikipedia (overview)", year: 2024, url: "https://en.wikipedia.org/wiki/Role_of_chance_in_scientific_discoveries" },
    { title: "Predictable serendipity: how new tools turn serendipity into systematic breakthroughs", venue: "Scientometrics", year: 2026, url: "https://link.springer.com/article/10.1007/s11192-025-05503-y" },
  ],
  "retraction-epidemiology-and-knowledge-base": [
    { title: "News: Crossref and Retraction Watch — open retraction data for the scientific community", venue: "Crossref", year: 2023, url: "https://www.crossref.org/blog/news-crossref-and-retraction-watch" },
    { title: "AI models are using material from retracted scientific papers", venue: "MIT Technology Review", year: 2025, url: "https://www.technologyreview.com/2025/09/23/1123897/ai-models-are-using-material-from-retracted-scientific-papers/" },
  ],
  "microbial-dark-matter-and-uncultured": [
    { title: "Functional and evolutionary significance of unknown genes from uncultivated taxa", venue: "Nature", year: 2023, url: "https://www.nature.com/articles/s41586-023-06955-z" },
    { title: "Approaches for accelerating microbial gene function discovery using artificial intelligence", venue: "Nature Microbiology", year: 2026, url: "https://www.nature.com/articles/s41564-025-02214-1" },
  ],
  "extremophiles-and-the-limits-of": [
    { title: "Relevance of Earth-Bound Extremophiles in the Search for Extraterrestrial Life", venue: "Life (MDPI)", year: 2022, url: "https://pubmed.ncbi.nlm.nih.gov/35108099/" },
    { title: "Mini-Review: Probing the limits of extremophilic life in extraterrestrial environment-simulated experiments", venue: "International Journal of Astrobiology", year: 2022, url: "https://www.cambridge.org/core/journals/international-journal-of-astrobiology/article/abs/minireview-probing-the-limits-of-extremophilic-life-in-extraterrestrial-environmentsimulated-experiments/0D5470821055110450CB64AD2A3CCBB2" },
    { title: "Navigating life in the extremes: a bibliometric exploration of extremophiles and astrobiology", venue: "International Journal of Astrobiology", year: 2023, url: "https://www.cambridge.org/core/journals/international-journal-of-astrobiology/article/navigating-life-in-the-extremes-a-bibliometric-exploration-of-extremophiles-and-astrobiology/D50EAEA3D9366BA14492E8A9ACBA8F85" },
  ],
  "an-early-warning-science-for": [
    { title: "Quantifying the Unexpected: a scientific approach to Black Swans", venue: "Physical Review Research", year: 2022, url: "https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.4.033079" },
    { title: "Quantifying the Unexpected: a scientific approach to Black Swans (preprint)", venue: "arXiv", year: 2022, url: "https://arxiv.org/abs/2201.12042" },
  ],
  "a-computable-expansion-law-for": [
    { title: "The TAP equation: evaluating combinatorial innovation in Biocosmology", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2204.14115" },
    { title: "Autocatalytic Sets Arising in a Combinatorial Model of Chemical Evolution", venue: "Life (MDPI)", year: 2022, url: "https://doi.org/10.3390/life12111703" },
  ],
  "cultural-accumulation-in-reinforcement-learning": [
    { title: "Artificial Generational Intelligence (arXiv preprint)", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2406.00392" },
  ],
  "quantum-simulators-probing-unknown-phases": [
    { title: "The Coming Decades of Quantum Simulation", venue: "arXiv", year: 2022, url: "https://arxiv.org/abs/2204.08905" },
  ],
  "anomaly-as-signal-cross-domain": [
    { title: "Building Machine Learning Challenges for Anomaly Detection in Science", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2503.02112" },
    { title: "Anomaly detection in Fink. I. Discovery, follow-up, and classification of unusual sources", venue: "arXiv", year: 2026, url: "https://arxiv.org/abs/2603.29511" },
  ],
  "mining-disciplinary-fissures-atlas-of": [
    { title: "Does the use of unusual combinations of datasets contribute to greater scientific impact?", venue: "PNAS", year: 2024, url: "https://www.pnas.org/doi/10.1073/pnas.2402802121" },
    { title: "Delayed Recognition: A Co-Citation Perspective", venue: "PMC", year: 2021, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8028384/" },
  ],
  "generic-early-warning-signals-for": [
    { title: "Tipping point detection and early warnings in climate, ecological, and human systems", venue: "Earth System Dynamics", year: 2024, url: "https://esd.copernicus.org/articles/15/1117/2024/" },
    { title: "Deep learning for predicting rate-induced tipping", venue: "Nature Machine Intelligence", year: 2024, url: "https://www.nature.com/articles/s42256-024-00937-0" },
  ],
  "the-detection-science-of-the": [
    { title: "Persistent microbial communities in hyperarid subsurface habitats of the Atacama Desert: Insights from intracellular DNA analysis", venue: "PNAS Nexus", year: 2024, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11037274/" },
    { title: "Life as We Don't Know It (alternative biochemistries and shadow life)", venue: "Astrobiology", year: 2024, url: "https://www.liebertpub.com/doi/full/10.1089/ast.2021.0103" },
    { title: "Subsurface Life on Earth as a Key to Unlock Extraterrestrial Mysteries", venue: "Life", year: 2024, url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12712870/" },
  ],
  "the-habitability-boundaries-of-alien": [
    { title: "Life as We Don't Know It", venue: "Astrobiology", year: 2024, url: "https://www.liebertpub.com/doi/full/10.1089/ast.2021.0103" },
    { title: "The Astrobiology Primer v2.0 (alternative solvents and biochemistries)", venue: "Astrobiology", year: 2016, url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4683543/" },
  ],
  "collider-anomaly-detection-transplanted-to": [
    { title: "A Classifier-Based Approach to Multi-Class Anomaly Detection for Astronomical Transients", venue: "RAS Techniques and Instruments", year: 2024, url: "https://academic.oup.com/rasti/article/doi/10.1093/rasti/rzae054/7914338" },
    { title: "Robust Anomaly Detection for Particle Physics Using Multi-Background Representation Learning", venue: "Machine Learning: Science and Technology", year: 2024, url: "https://iopscience.iop.org/article/10.1088/2632-2153/ad780c/meta" },
    { title: "DisCo Fever: Robust Networks Through Distance Correlation", venue: "arXiv (hep-ph) / JHEP", year: 2020, url: "https://arxiv.org/abs/2001.05310" },
  ],
  "functorial-cross-domain-structure-transport": [
    { title: "Category-Theoretical and Topos-Theoretical Frameworks in Machine Learning: A Survey", venue: "Axioms (MDPI)", year: 2025, url: "https://www.mdpi.com/2075-1680/14/3/204" },
    { title: "Towards a Categorical Foundation of Deep Learning: A Survey", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2410.05353" },
  ],
  "observation-native-forecasting-end-to": [
    { title: "GraphDOP: Towards skilful data-driven medium-range weather forecasts learnt and initialised directly from observations", venue: "arXiv", year: 2024, url: "https://arxiv.org/abs/2412.15687" },
    { title: "An update on AI-DOP: skilful weather forecasts produced directly from observations", venue: "ECMWF Newsletter", year: 2025, url: "https://www.ecmwf.int/en/newsletter/182/earth-system-science/update-ai-dop-skilful-weather-forecasts-produced-directly" },
  ],
  "ai-adjoint-sensitivity-backpropagating-through": [
    { title: "Testing the Limit of Atmospheric Predictability with a Machine Learning Weather Model", venue: "arXiv", year: 2025, url: "https://arxiv.org/abs/2504.20238" },
  ],
  "threshold-and-multiparty-fhe-shattering": [
    { title: "Threshold FHE with Efficient Asynchronous Decryption", venue: "IACR ePrint", year: 2025, url: "https://eprint.iacr.org/2025/712" },
    { title: "Robust Multiparty Computation from Threshold Encryption Based on RLWE", venue: "IACR ePrint", year: 2024, url: "https://eprint.iacr.org/2024/1285" },
  ],
  "positive-tipping-cascades-engineering-self": [
    { title: "A method to identify positive tipping points to accelerate low-carbon transitions and actions to trigger them", venue: "Sustainability Science", year: 2025, url: "https://link.springer.com/article/10.1007/s11625-025-01704-9" },
    { title: "Pathways for prevention of cascading tipping points", venue: "Communications Earth & Environment", year: 2025, url: "https://www.nature.com/articles/s43247-025-02662-x" },
  ],
  "computable-criteria-for-rate-induced": [
    { title: "Rate-induced tipping in ecosystems and climate: the role of unstable states, basin boundaries and transient dynamics", venue: "Nonlinear Processes in Geophysics", year: 2023, url: "https://npg.copernicus.org/articles/30/481/2023/" },
  ],
};

/** Real references for one island, or an empty list when the atlas record
 *  carried none beyond the headline citation. Never fabricated. */
export function literatureBySlug(slug: string): IslandReference[] {
  return LITERATURE_BY_SLUG[slug] ?? [];
}

/** Islands that currently carry at least one extra reference. */
export const LITERATURE_SLUGS: readonly string[] = Object.keys(LITERATURE_BY_SLUG);
