/**
 * GENERATED by scripts/generate-structure-index.mjs — do not edit by hand.
 *
 * How much written body each structure has, in three integers, small enough to
 * ship eagerly. Absence from this record means the structure has a statement
 * and nothing else — which is real content about the catalogue, not a loading
 * state, so a consumer may render the absence directly.
 *
 * The body itself (origin, minimal form, textbook substrates, relations,
 * what it gets mistaken for) lives in `structures.ts` and its depth files and
 * must stay behind a dynamic `import()`.
 */

export interface StructureReadingIndexEntry {
  /** Textbook instances written for this structure. */
  substrates: number;
  /** Distinct disciplines those instances come from. */
  fields: number;
  /** Relations a reader can follow from it: authored here plus pointing at it. */
  relations: number;
}

export const STRUCTURE_READING_INDEX: Record<string, StructureReadingIndexEntry> = {
  "struct://xfrontier/synchronization": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/network-cascade": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/scaling": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/intervention-identifiability": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/anomaly-as-signal": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/executable-knowledge": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/substrate-local-learning": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/model-reality-loop": {
    "substrates": 4,
    "fields": 4,
    "relations": 3
  },
  "struct://xfrontier/variational-free-energy": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/adjoint-functors": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/open-set-recognition": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/error-correcting-redundancy": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/selection-bias-absence": {
    "substrates": 4,
    "fields": 4,
    "relations": 11
  },
  "struct://xfrontier/covariate-shift-transfer": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/fisher-precision-limit": {
    "substrates": 4,
    "fields": 4,
    "relations": 8
  },
  "struct://xfrontier/transitive-link-prediction": {
    "substrates": 3,
    "fields": 3,
    "relations": 2
  },
  "struct://xfrontier/recursive-bayesian-filter": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/shannon-entropy": {
    "substrates": 4,
    "fields": 4,
    "relations": 5
  },
  "struct://xfrontier/assembly-description-length": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/distributed-field-observability": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/stateful-in-materia-computation": {
    "substrates": 4,
    "fields": 4,
    "relations": 3
  },
  "struct://xfrontier/nash-equilibrium": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/ising-mean-field": {
    "substrates": 3,
    "fields": 3,
    "relations": 9
  },
  "struct://xfrontier/branching-criticality": {
    "substrates": 3,
    "fields": 3,
    "relations": 7
  },
  "struct://xfrontier/graph-laplacian-spectrum": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/gauge-equivariance": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/information-geometry": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/optimal-transport": {
    "substrates": 4,
    "fields": 4,
    "relations": 5
  },
  "struct://xfrontier/laplace-equation": {
    "substrates": 4,
    "fields": 4,
    "relations": 3
  },
  "struct://xfrontier/diffusion-equation": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/negative-feedback-control": {
    "substrates": 4,
    "fields": 4,
    "relations": 8
  },
  "struct://xfrontier/renormalization-group": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/optimal-stopping": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/reaction-diffusion": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/extreme-value-theory": {
    "substrates": 4,
    "fields": 4,
    "relations": 5
  },
  "struct://xfrontier/anomalous-diffusion": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/bayesian-surprise": {
    "substrates": 4,
    "fields": 4,
    "relations": 5
  },
  "struct://xfrontier/power-laws-scale-free": {
    "substrates": 4,
    "fields": 4,
    "relations": 9
  },
  "struct://xfrontier/replicator-dynamics": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/least-action-variational-principles": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/maximum-entropy-inference": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/attractor-networks-hopfield": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/sparse-coding-compressed-sensing": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/critical-slowing-down": {
    "substrates": 4,
    "fields": 4,
    "relations": 8
  },
  "struct://xfrontier/self-assembly": {
    "substrates": 3,
    "fields": 3,
    "relations": 2
  },
  "struct://xfrontier/landauer-erasure-cost": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/quorum-sensing": {
    "substrates": 4,
    "fields": 4,
    "relations": 2
  },
  "struct://xfrontier/verification-asymmetry": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/computational-lower-bounds": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/communication-complexity": {
    "substrates": 3,
    "fields": 3,
    "relations": 2
  },
  "struct://xfrontier/undecidability": {
    "substrates": 4,
    "fields": 4,
    "relations": 2
  },
  "struct://xfrontier/tacit-craft-explicitation": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/within-subject-control": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/aggregating-independent-judgements": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/negative-control": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/zero-knowledge-verification": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/traceability-chain": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/injected-randomness": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/preregistration": {
    "substrates": 4,
    "fields": 4,
    "relations": 3
  },
  "struct://xfrontier/counterfactual-trace": {
    "substrates": 3,
    "fields": 3,
    "relations": 2
  },
  "struct://xfrontier/self-organised-criticality": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/phase-separation": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/spontaneous-modularity": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/conjugate-uncertainty": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/finite-time-dissipation": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/robustness-efficiency-tradeoff": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/cognitive-bandwidth-ceiling": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/metric-distortion": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/parallel-speedup-ceiling": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/unit-of-individuality": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/measurement-backaction": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/selective-gate": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/ex-vivo-reconstitution": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/intermediate-rung": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/waste-as-feedstock": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/resistance-rotation": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/leverage-point": {
    "substrates": 3,
    "fields": 3,
    "relations": 7
  },
  "struct://xfrontier/natural-experiment": {
    "substrates": 4,
    "fields": 4,
    "relations": 5
  },
  "struct://xfrontier/alternative-mechanism-panel": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/standardisation-lowers-the-bar": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/dissipation-floor": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/impossibility-theorem": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/no-free-lunch": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/causal-propagation-limit": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/scale-separation-failure": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/minimum-viable-size": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/explore-exploit-tension": {
    "substrates": 4,
    "fields": 4,
    "relations": 8
  },
  "struct://xfrontier/two-error-tradeoff": {
    "substrates": 4,
    "fields": 4,
    "relations": 10
  },
  "struct://xfrontier/commensuration-cost": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/data-movement-dominates": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/surface-volume-crossover": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/limiting-factor": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/niche-construction": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/deep-time-accumulation": {
    "substrates": 3,
    "fields": 3,
    "relations": 11
  },
  "struct://xfrontier/bullwhip-amplification": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/propagule-pressure": {
    "substrates": 3,
    "fields": 3,
    "relations": 2
  },
  "struct://xfrontier/archival-decay": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/commons-congestion": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/small-world": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/superposition-ordering": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/template-copying-error": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/boundary-work": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/tolerance-evolution": {
    "substrates": 4,
    "fields": 4,
    "relations": 3
  },
  "struct://xfrontier/delay-induced-oscillation": {
    "substrates": 4,
    "fields": 4,
    "relations": 6
  },
  "struct://xfrontier/network-externality-lockin": {
    "substrates": 3,
    "fields": 3,
    "relations": 7
  },
  "struct://xfrontier/drift-fixation": {
    "substrates": 3,
    "fields": 3,
    "relations": 7
  },
  "struct://xfrontier/path-dependence": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/cohort-inertia": {
    "substrates": 4,
    "fields": 4,
    "relations": 2
  },
  "struct://xfrontier/hourglass-waist": {
    "substrates": 3,
    "fields": 3,
    "relations": 7
  },
  "struct://xfrontier/lexicalisation": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/grammaticalisation": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/information-asymmetry": {
    "substrates": 3,
    "fields": 3,
    "relations": 6
  },
  "struct://xfrontier/slow-variable-creep": {
    "substrates": 3,
    "fields": 3,
    "relations": 8
  },
  "struct://xfrontier/precedent-accumulation": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/frozen-accident": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/fatigue-accumulation": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/red-queen": {
    "substrates": 4,
    "fields": 4,
    "relations": 3
  },
  "struct://xfrontier/perturb-and-read": {
    "substrates": 4,
    "fields": 4,
    "relations": 7
  },
  "struct://xfrontier/costly-signal": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/commitment-device": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/dormant-seed-bank": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/controlled-inoculation": {
    "substrates": 3,
    "fields": 3,
    "relations": 4
  },
  "struct://xfrontier/devolving-control": {
    "substrates": 3,
    "fields": 3,
    "relations": 3
  },
  "struct://xfrontier/shift-left": {
    "substrates": 3,
    "fields": 3,
    "relations": 5
  },
  "struct://xfrontier/self-nonself-discrimination": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  },
  "struct://xfrontier/rebuild-from-description": {
    "substrates": 4,
    "fields": 4,
    "relations": 4
  }
};

export function structureReadingIndex(id: string): StructureReadingIndexEntry | undefined {
  return STRUCTURE_READING_INDEX[id];
}
