import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
const snapshot = JSON.parse(readFileSync(new URL('../src/data/exploration-catalog.json', import.meta.url), 'utf8'));
const launch = async (page: import('@playwright/test').Page) => { await page.goto('/'); await page.getByRole('button', { name: /领域碰撞/ }).first().click(); };
test.beforeEach(async ({ page }) => { await page.route('**/api/xfrontier/catalog', (route) => route.fulfill({ status: 503, json: { error: 'xfrontier_unavailable' } })); });
test('curiosity branches and recovers without scores or required stages', async ({ page }) => {
  await launch(page); const dialog = page.getByRole('dialog', { name: '领域碰撞' });
  await expect(dialog.getByText('离线资料', { exact: true })).toBeVisible();
  await expect(dialog.getByRole('navigation', { name: '跨领域主题' }).getByRole('button')).toHaveCount(6);
  await expect(dialog.getByText(/实践印记|继续下一步/)).toHaveCount(0);
  await dialog.getByRole('button', { name: '带着这个问题出发' }).click();
  await dialog.getByLabel('此刻，你想追问什么？').fill('相似可能来自测量滤波；先控制采样过程。');
  await dialog.getByRole('button', { name: '留下思考', exact: true }).click();
  await dialog.locator('.fi-collision-branches button').first().click();
  const data = await page.evaluate(() => JSON.parse(localStorage.getItem('fi-collision-expeditions-v1')!));
  expect(data.entries).toHaveLength(2); expect(data.entries[1].parentId).toBe(data.entries[0].id);
  expect(data.entries[0].source.datasetVersion).toBe(snapshot.datasetVersion);
  const downloaded = page.waitForEvent('download'); await dialog.getByRole('button', { name: '导出探索记录' }).click();
  expect((await downloaded).suggestedFilename()).toBe('frontier-expedition.md');
  await page.keyboard.press('Escape'); await expect(dialog).not.toBeVisible();
  await expect(page.getByRole('button', { name: /领域碰撞/ }).first()).toBeFocused();
  await page.reload(); await page.getByRole('button', { name: /领域碰撞/ }).first().click();
  await expect(page.getByLabel('此刻，你想追问什么？')).toBeVisible();
  await page.getByRole('button', { name: '我的航迹', exact: true }).click();
  await expect(page.locator('.fi-collision-trail li')).toHaveCount(2);
  await page.locator('.fi-collision-trail button').first().click();
  await expect(page.getByText('相似可能来自测量滤波；先控制采样过程。', { exact: true })).toBeVisible();
});
test('mobile has a readable map and focused writing viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await launch(page);
  const dialog = page.getByRole('dialog', { name: '领域碰撞' });
  await expect(dialog.getByRole('button', { name: '关闭' })).toBeInViewport();
  await dialog.getByRole('searchbox').fill('不存在的词 xyzzy');
  await expect(dialog.getByText('没有匹配的碰撞。换一个关键词试试。')).toBeVisible();
  await dialog.getByRole('searchbox').fill('');
  const theme = dialog.getByRole('navigation', { name: '跨领域主题' });
  await expect(theme.getByRole('button').first()).toBeInViewport();
  expect((await theme.boundingBox())!.height).toBeGreaterThanOrEqual(44);
  await dialog.locator('.fi-voyage-island').first().click();
  await dialog.getByRole('button', { name: '带着这个问题出发' }).click();
  await expect(dialog.getByLabel('此刻，你想追问什么？')).toBeInViewport();
  await dialog.getByLabel('此刻，你想追问什么？').fill('先找不同机制但表现相同的反例。');
  await expect(dialog.getByRole('button', { name: '留下思考', exact: true })).toBeInViewport();
  await dialog.getByRole('button', { name: '回到问题群岛', exact: true }).click();
  await expect(dialog.locator('.fi-voyage-island').first()).toBeFocused();
  expect(await dialog.evaluate((el) => el.scrollWidth <= innerWidth && document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('AI proposals follow context and remain separate from observations', async ({ page }) => {
  await page.route('**/api/research-assistant/capability', (r) => r.fulfill({ json: { state: 'ready', model: 'contract-test' } }));
  let request: any;
  await page.route('**/api/research-assistant/explore', (r) => { request = r.request().postDataJSON(); return r.fulfill({ json: { reply: '测试提案：先排除共同外部驱动。', moves: [{ kind: 'challenge', title: '检查共同驱动', question: '控制外部驱动后，联系还存在吗？', reason: '共同原因能产生相关性。', boundary: '相关性不能证明相同机制。', questionIds: request.questionIds }], datasetVersion: snapshot.datasetVersion, model: 'contract-test', createdAt: new Date().toISOString(), sources: [] } }); });
  await launch(page); await page.getByRole('button', { name: '带着这个问题出发' }).click();
  await page.getByLabel('此刻，你想追问什么？').fill('我怀疑测量噪声。');
  await page.getByRole('button', { name: '找一个能反驳它的解释', exact: true }).click();
  await expect(page.getByRole('button', { name: '沿这句追问继续' })).toBeVisible();
  expect(request.message).toContain('找一个能反驳它的解释'); expect(request.message).toContain('我怀疑测量噪声。');
  await page.getByRole('button', { name: '沿这句追问继续' }).click();
  await expect(page.locator('.fi-collision-current-question')).toHaveText('控制外部驱动后，联系还存在吗？');
  const entry = await page.evaluate(() => JSON.parse(localStorage.getItem('fi-collision-expeditions-v1')!).entries[0]);
  expect(entry.outcome).toBe('unrun'); expect(entry.notes.some((n: any) => n.kind === 'ai')).toBe(true); expect(entry.notes.at(-1).attribution).toContain('未验证');
});
test('an actual toy-model run returns to the trail without a required prediction', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await launch(page);
  await page.getByRole('button', { name: '带着这个问题出发' }).click();
  await page.getByText('在一个可运行的模型里试一试', { exact: true }).click();
  await page.getByRole('button', { name: '同步：萤火虫、心肌与电网' }).click();
  const model = page.getByRole('dialog', { name: '亲手搭一个会跑的模型' });
  await model.getByRole('button', { name: '运行', exact: true }).click();
  await expect(model.getByText('这次是先观察，没有事前预测。可以带着读数提出下一次问题。')).toBeVisible();
  await model.getByRole('button', { name: '把这次运行放进考察札记' }).click();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog', { name: '领域碰撞' })).toBeVisible();
  await expect(page.getByText('模型观察', { exact: true })).toBeVisible();
  const notes = await page.evaluate(() => JSON.parse(localStorage.getItem('fi-collision-expeditions-v1')!).entries[0].notes);
  const receipt = JSON.parse(notes.find((n: any) => n.kind === 'model').attachment);
  expect(receipt.prediction).toBeNull(); expect(receipt.observation.steps).toBeGreaterThan(0); expect(receipt.observation.final).not.toBe(receipt.observation.initial);
});
test('failed island founding stays open without false success', async ({ page }) => {
  await page.route('**/api/islands', async (r) => r.request().method() === 'POST' ? r.fulfill({ status: 503, json: { error: 'offline' } }) : r.continue());
  await launch(page); const dialog = page.getByRole('dialog', { name: '领域碰撞' });
  await dialog.getByRole('button', { name: '数学桥', exact: true }).click(); await dialog.getByRole('button', { name: '以这座桥建立问题岛' }).click();
  await expect(dialog.getByRole('alert')).toContainText('创建未成功'); await expect(dialog).toBeVisible(); await expect(page.getByText(/于桥上升起/)).toHaveCount(0);
});

 test('keyboard reaches the final source disclosure and wraps after it', async ({ page }) => {
  await page.route('**/api/xfrontier/question/*', r => r.fulfill({ status: 503, json: { error: 'offline' } }));
  await launch(page);
  const dialog = page.getByRole('dialog', { name: '领域碰撞' });
  await dialog.locator('.fi-collision-branches button').last().focus();
  await page.keyboard.press('Tab');
  const source = dialog.locator('.fi-collision-provenance > summary');
  await expect(source).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(dialog.getByRole('button', { name: '重试核对出处' })).toBeVisible();
  await page.keyboard.press('Tab');
  await expect(dialog.getByRole('button', { name: '重试核对出处' })).toBeFocused();
  await page.keyboard.press('Tab');
  await expect(dialog.getByRole('button', { name: '问题群岛', exact: true })).toBeFocused();
});
